import {
  Z_BASE,
  Z_STICKY_IN_SCROLL,
  Z_FOCUS_DIM,
  Z_FOCUS_COMPANION,
  Z_GLOBAL_CHROME,
  Z_FOCUS_ACTIVE,
  Z_DROPDOWN,
  Z_POPOVER,
  Z_MODAL,
  Z_MODAL_NESTED,
  Z_OVERLAY_BACKDROP,
  Z_OVERLAY,
  Z_TOAST,
  Z_ERROR_BOUNDARY,
} from '@/constants/zIndex';

/**
 * LAYOUT CONSTANTS (Single Source of Truth)
 *
 * Z-index values mirror src/constants/zIndex.ts — do not duplicate numbers here.
 */
export const LAYOUT = {
  SIDEBAR_WIDTH: '30rem',
  SIDEBAR_WIDTH_WIDE: '35rem',
  HEADER_HEIGHT: '4rem',
  HEADER_HEIGHT_MOBILE: '3.5rem',
  MOBILE_NAV_HEIGHT: '4rem',

  BREAKPOINTS: {
    MD: 768,
    LG: 1024,
    XL: 1280,
    '2XL': 1536,
  },

  Z: {
    BASE: Z_BASE,
    FOCUS_DIM: Z_FOCUS_DIM,
    FOCUS_COMPANION: Z_FOCUS_COMPANION,
    GLOBAL_CHROME: Z_GLOBAL_CHROME,
    FOCUS_ACTIVE: Z_FOCUS_ACTIVE,
    DROPDOWN: Z_DROPDOWN,
    POPOVER: Z_POPOVER,
    MODAL: Z_MODAL,
    MODAL_OVERLAY: Z_MODAL_NESTED,
    OVERLAY_BACKDROP: Z_OVERLAY_BACKDROP,
    MODAL_DIM: Z_OVERLAY,
    TOAST: Z_TOAST,
    ERROR_BOUNDARY: Z_ERROR_BOUNDARY,
  },
} as const;
