/**
 * Catalogo dominio Macrofase C — CONGELATO.
 * Dati editoriali: rigenerare con scripts/build-packing-domain-catalog.ts
 */

import { CATEGORY_ORDER } from './packingCategories';
import type { PackingStandardItemTier } from '@/types/packingCatalog';
import type {
  PackingCategoryItemMap,
  PackingTemplateCatalogMap,
  PackingStandardCatalogItem,
  PackingAiCatalogEntry,
  PackingDomainValidationReport,
} from './packingDomainCatalogTypes';
import { validatePackingDomainCatalogData } from './packingDomainCatalogValidation';

export * from './packingDomainCatalogTypes';

export const PACKING_STANDARD_CATALOG = {
  Abbigliamento: [
    'Intimo',
    'Calze',
    'T-shirt',
    'Pantaloni',
    'Pigiama',
    'Scarpe da giorno',
    'Canotta',
    'Cintura',
    'Maglietta manica lunga',
    'Giacca leggera',
  ],
  Igiene: [
    'Spazzolino',
    'Dentifricio',
    'Deodorante',
    'Shampoo',
    'Bagnoschiuma',
    'Spazzola capelli',
    'Assorbenti',
    'Crema idratante',
    'Asciugamano',
    'Telo doccia',
  ],
  Documenti: [
    'Documento identità',
    'Tessera sanitaria',
    'Carte di pagamento',
    'Contanti',
    'Prenotazione alloggio',
    'Biglietti trasporto',
    'Copia documenti',
    'Assicurazione viaggio',
    'Patente di guida',
    'Voucher attività',
  ],
  Elettronica: [
    'Smartphone',
    'Caricabatterie smartphone',
    'Cavo ricarica',
    'Cavo di riserva',
    'Power bank',
    'Auricolari',
    'Caricabatterie multiporta',
    'Adattatore presa universale',
    'Smartwatch',
    'Caricabatterie wireless',
  ],
  Farmaci: [
    'Farmaci personali abituali',
    'Antidolorifico',
    'Cerotti misti',
    'Disinfettante',
    'Antiacido / antidiarroico',
  ],
  Accessori: [
    'Portafoglio',
    'Zaino da giorno',
    'Borraccia',
    'Lucchetto valigia',
    'Orologio',
  ],
  Extra: [
    'Snack',
    'Sacchetto spesa pieghevole',
    'Libro',
    'Giochi carte',
    'Thermos',
  ],
  Bambini: [
    'Pannolini',
    'Salviette bimbo',
    'Cambio abbigliamento bambino',
    'Biberon',
    'Snack bambino',
  ],
  Animali: [
    'Cibo pet',
    'Ciotole',
    'Guinzaglio',
    'Sacchetti igienici',
    'Libretto sanitario pet',
  ],
} as const satisfies PackingCategoryItemMap;

export const PACKING_TEMPLATE_CATALOG = {
  mare: {
    Abbigliamento: [
      'Costume',
      'Infradito',
      'Shorts',
      'Sandali',
      'Copricostume',
      'Maglietta UV',
      'Bermuda',
      'Canotta estiva',
      'Cappello sole',
      'Camicia leggera estiva',
    ],
    Igiene: [
      'Crema solare',
      'Doposole',
      'Shampoo antisale',
      'Balsamo capelli',
      'Gel doccia',
      'Salviette corpo',
      'Detergente viso',
      'After-sun capelli',
      'Accappatoio',
      'Asciugamano microfibra',
    ],
    Documenti: [
      'Prenotazione spiaggia',
      'Voucher attività mare',
      'Polizza sport acquatici',
      'Prenotazione diving',
      'Mappa costa',
      'Tessera club nautico',
      'Assicurazione annullamento',
      'Permesso barca',
      'Documenti minori',
      'Voucher noleggio',
    ],
    Elettronica: [
      'Custodia impermeabile',
      'Action cam',
      'Caricatore solare',
      'Power bank',
      'Adattatore auto',
      'Supporto telefono',
      'Cavo lungo',
      'Speaker compatto',
      'Luce notturna',
      'Asciugacapelli mini',
    ],
    Farmaci: [
      'Crema punture medusa',
      'Antistaminico',
      'Soluzione fisiologica',
      'Cerotti ampolla',
      'Integratore sali',
      'Collirio',
      'Antinfiammatorio',
      'Gel post-ustione',
      'Pomata antibiotica topica',
      'Spray raffreddamento',
    ],
    Accessori: [
      'Borsa mare',
      'Sacca impermeabile',
      'Occhiali da sole',
      'Telo zaino spiaggia',
      'Cappello cordino',
      'Tappi orecchie nuoto',
      'Custodia occhiali',
      'Borsa rete',
      'Zaino da giorno',
      'Borraccia',
    ],
    Extra: [
      'Telo mare',
      'Maschera e boccaglio',
      'Pallone spiaggia',
      'Giochi spiaggia',
      'Frisbee',
      'Secchiello bambini',
      'Ciambella nuoto',
      'Asciugamano mare',
      'Libro',
      'Speaker compatto',
    ],
    Bambini: [
      'Costume bambino',
      'Cappello bambino SPF',
      'Scarpe acqua',
      'Giochi sabbia',
      'Salvagente',
      'Crema solare bambini',
      'Copricostume bimbo',
      'T-shirt ricambio',
      'Pantaloncini',
      'Occhiali bimbo',
    ],
    Animali: [
      'Asciugamano pet',
      'Acqua fresca pet',
      'Giubbottino',
      'Paw balm',
      'Telo auto',
      'Giochi',
      'Salviette pet',
      'Trasportino',
      'Coperta pet',
      'Ombra pet',
    ],
  },
  lago: {
    Abbigliamento: [
      'Costume',
      'Infradito',
      'Shorts',
      'Sandali',
      'Ciabatte',
      'T-shirt leggera',
      'Pantalone leggero',
      'Canotta',
      'Cappello sole',
      'Felpa',
    ],
    Igiene: [
      'Crema solare',
      'Doposole',
      'Shampoo delicato',
      'Balsamo labbra SPF',
      'Gel doccia',
      'Salviette',
      'Detergente viso',
      'Crema mani',
      'Deodorante ricarica',
      'Asciugamano microfibra',
    ],
    Documenti: [
      'Permesso pesca',
      'Mappa sentieri',
      'Prenotazione traghetti',
      'Voucher barca',
      'Guida area',
      'Biglietti escursioni',
      'Assicurazione sport',
      'Mappa lago',
      'Documenti pet area',
      'Prenotazione escursione',
    ],
    Elettronica: [
      'Custodia impermeabile',
      'Fotocamera compatta',
      'Power bank',
      'Caricabatterie auto',
      'Supporto telefono',
      'Cavo lungo',
      'Luce frontale',
      'Adattatore',
      'Batteria ricambio',
      'Speaker compatto',
    ],
    Farmaci: [
      'Repellente insetti',
      'Pomata post-puntura',
      'Antistaminico',
      'Antinfiammatorio',
      'Cerotti',
      'Crema antifungina',
      'Gel muscolare',
      'Disinfettante',
      'Collirio',
      'Integratore',
    ],
    Accessori: [
      'Zaino da giorno',
      'Sacca stagna',
      'Borraccia',
      'Occhiali da sole',
      'Telo picnic',
      'Cappello sole',
      'Custodia documenti',
      'Borsa frigo',
      'Custodia impermeabile',
      'Organizer valigia',
    ],
    Extra: [
      'Telo picnic',
      'Giochi acqua',
      'Binocolo',
      'Thermos',
      'Libro',
      'Carte giochi',
      'Mappa area',
      'Giochi outdoor',
      'Amaca leggera',
      'Snack energetici',
    ],
    Bambini: [
      'Costume bambino',
      'Scarpe acqua',
      'Giochi acqua',
      'Cappello bimbo',
      'T-shirt ricambio',
      'Pantaloncini',
      'Salvagente',
      'Crema solare bambini',
      'Coperta leggera',
      'Giubbino',
    ],
    Animali: [
      'Giubbottino galleggiante',
      'Telo auto',
      'Giochi acqua',
      'Borraccia pet',
      'Coperta pet',
      'Trasportino',
      'Ciotole pieghevoli',
      'Giochi',
      'Salviette pet',
      'Zampa protection',
    ],
  },
  montagna: {
    Abbigliamento: [
      'Scarponi trekking',
      'Pile',
      'Giacca antivento',
      'Giacca impermeabile',
      'Pantalone trekking',
      'Calze tecniche',
      'Buff',
      'Guanti',
      'Berretto',
      'Maglia termica',
    ],
    Igiene: [
      'Crema protezione alta',
      'Burrocacao',
      'Crema mani riparatrice',
      'Detergente delicato',
      'Balsamo labbra',
      'Sapone solido',
      'Crema viso barriera',
      'Idratante intenso',
      'Gel doccia montagna',
      'Asciugamano microfibra',
    ],
    Documenti: [
      'Carta sentieri',
      'Permesso parco',
      'Mappa trekking',
      'Assicurazione SAR',
      'Licenza rifugio',
      'Prenotazione guide',
      'Bollettino meteo',
      'Registro rifugio',
      'Permesso arrampicata',
    ],
    Elettronica: [
      'Frontale',
      'Power bank',
      'GPS esterno',
      'Batteria frontale',
      'Cavo lungo',
      'Action cam',
      'Radio',
      'Termometro elettronico',
      'Caricabatterie robusto',
      'Batteria esterna camera',
    ],
    Farmaci: [
      'Farmaci mal di montagna',
      'Cerotti vesciche',
      'Gel muscolare',
      'Integratori sali',
      'Antistaminico',
      'Benda elastica',
      'Antidolorifico forte',
      'Pomata articolazioni',
      'Crema labbra medicata',
      'Antinfiammatorio',
    ],
    Accessori: [
      'Bastoncini trekking',
      'Borraccia termica',
      'Coprizaino',
      'Fischietto',
      'Cartella mappe',
      'Moschettoni',
      'Dry bag',
      'Imbracatura leggera',
      'Zaino da giorno',
      'Borraccia',
    ],
    Extra: [
      'Coltellino',
      'Binocolo',
      'Carta e penna',
      'Fodera sacco',
      'Filtro acqua',
      'Fischietto',
      'Sacca compressione',
      'Thermos',
      'Corda leggera',
      'Kit corda',
    ],
    Bambini: [
      'Zaino bimbo',
      'Felpa bimbo',
      'Guanti bimbo',
      'Pantalone trekking bimbo',
      'Giacca impermeabile bimbo',
      'Berretto bimbo',
      'Calze ricambio',
      'Termico bimbo',
      'Scarpe chiuse',
      'Buff bimbo',
    ],
    Animali: [
      'Scarpette zampine',
      'Gilet riflettente',
      'Borraccia pet',
      'Kit pronto soccorso pet',
      'Imbracatura',
      'Coperta',
      'Giochi',
      'Salviette pet',
      'Guinzaglio',
      'Pettorina',
    ],
  },
  cultura: {
    Abbigliamento: [
      'Scarpe da passeggiata',
      'Pantaloni comodi',
      'Polo',
      'Cardigan',
      'Sciarpa leggera',
      'Sneaker',
      'Pantalone leggero',
      'Blazer casual',
      'Gonna o vestito',
      'Camicia casual',
    ],
    Igiene: [
      'Gel mani',
      'Salviette igienizzanti',
      'Deodorante travel',
      'Crema mani',
      'Schiuma da barba',
      'Balsamo barba',
      'Kit manicure',
      'Profumo leggero',
      'Dischetti struccanti',
      'Spray igienizzante',
    ],
    Documenti: [
      'Biglietti musei',
      'City pass',
      'Mappa offline',
      'Audioguida',
      'Prenotazioni ristorante',
      'Biglietti teatro',
      'Abbonamento trasporti',
      'Prenotazione tour',
      'Guida turistica',
      'Lista orari monumenti',
    ],
    Elettronica: [
      'E-reader',
      'Fotocamera compatta',
      'Power bank',
      'Adattatore audio guida',
      'Cavo lungo',
      'Caricabatterie foto',
      'Hard disk portatile',
      'Mouse pieghevole',
      'Selfie stick',
      'Hub USB',
    ],
    Farmaci: [
      'Cerotti vesciche',
      'Antistaminico',
      'Antinfiammatorio',
      'Integratore',
      'Disinfettante',
      'Antiacido',
      'Spray nasale',
      'Melatonina',
      'Antidolorifico',
      'Collirio',
    ],
    Accessori: [
      'Zaino da giorno',
      'Portafoglio RFID',
      'Borsa crossbody',
      'Ombrello',
      'Portadocumenti',
      'Cintura portasoldi',
      'Occhiali da sole',
      'Borsa pieghevole',
      'Organizer cavi',
      'Beauty case',
    ],
    Extra: [
      'Taccuino',
      'Penna',
      'Borsa shopping',
      'Snack energetici',
      'Mappa cartacea',
      'Giochi viaggio',
      'Carte',
      'Libro',
      'Rivista',
      'Diario viaggio',
    ],
    Bambini: [
      'Zaino bimbo',
      'Snack lunghi',
      'Giochi quiet',
      'Libro bambini',
      'Penna colori',
      'Merenda',
      'Acqua bimbo',
      'Giochi magnetici',
      'Auricolari limitati',
      'Documenti tasca',
    ],
    Animali: [
      'Borsa pet urbano',
      'Pettorina',
      'Salviette pet',
      'Giochi quiet',
      'Trasportino',
      'Cibo porzionato',
      'Giochi',
      'Ciotole',
      'Borraccia pet',
      'Documenti pet',
    ],
  },
  business: {
    Abbigliamento: [
      'Camicia elegante',
      'Pantalone elegante',
      'Blazer',
      'Scarpe eleganti',
      'Cravatta',
      'Calze eleganti',
      'Canottiera',
      'Giacca completo',
      'Abito serata',
      'Pantalone serata',
    ],
    Igiene: [
      'Deodorante long-lasting',
      'Crema mani non unta',
      'Schiuma da barba',
      'Balsamo barba',
      'Kit manicure',
      'Profumo leggero',
      'Crema viso',
      'Limatura unghie',
      'Salviette',
      'Deodorante ricarica',
    ],
    Documenti: [
      'Biglietti da visita',
      'Agenda',
      'Badge evento',
      'Contratti',
      'Itinerario voli',
      'Prenotazione hotel',
      'Biglietti treno',
      'Biglietti aereo',
    ],
    Elettronica: [
      'Laptop',
      'Caricabatterie laptop',
      'Mouse wireless',
      'Hub USB-C',
      'Adattatore HDMI',
      'Pendrive',
      'Webcam',
      'Microfono cuffia',
      'Hard disk esterno',
      'Docking travel',
    ],
    Farmaci: [
      'Farmaci cinetosi',
      'Antistaminico non sedante',
      'Antiacido',
      'Integratore',
      'Cerotti',
      'Collirio',
      'Antinfiammatorio',
      'Melatonina',
      'Spray nasale',
      'Antidolorifico',
    ],
    Accessori: [
      'Borsa laptop',
      'Organizer cavi',
      'Portadocumenti',
      'Portabadge',
      'Lucchetto TSA',
      'Borsa elegante',
      'Astuccio penne',
      'Custodia abiti',
      'Zaino da giorno',
      'Borraccia',
    ],
    Extra: [
      'Blocco note',
      'Penne',
      'Snack meeting',
      'Thermos',
      'Rivista',
      'Caramelle',
      'Carta appunti',
      'Taccuino',
      'Snack',
      'Libro',
    ],
    Bambini: [
      'Snack silenziosi',
      'Giochi auto',
      'Auricolari bimbo',
      'Peluche',
      'Cambio outfit',
      'Libro',
      'Giochi',
      'Merenda',
      'Borraccia bimbo',
      'Tablet contenuto',
    ],
    Animali: [
      'Ciotole',
      'Tappetino',
      'Salviette',
      'Giochi',
      'Borsa pet',
      'Cibo porzionato',
      'Guinzaglio',
      'Pettorina',
      'Borraccia pet',
      'Trasportino',
    ],
  },
  weekend: {
    Abbigliamento: [
      'Pantaloncini',
      'Polo',
      'Jeans',
      'Sneaker',
      'Outfit serata',
      'Felpa',
      'Maglione leggero',
      'Cappello',
      'Sciarpa leggera',
      'Giacca packable',
    ],
    Igiene: [
      'Kit igiene travel size',
      'Deodorante mini',
      'Shampoo mini',
      'Dentifricio mini',
      'Sapone solido',
      'Balsamo labbra',
      'Gel doccia mini',
      'Salviette',
      'Spazzolino ricambio',
      'Crema mani mini',
    ],
    Documenti: [
      'Prenotazione ristorante',
      'Biglietto evento',
      'Prenotazione hotel',
      'Mappa quartiere',
      'Voucher esperienza',
      'Conferma transfer',
      'Biglietto concerto',
      'Documenti noleggio auto',
      'Lista attività',
      'Prenotazione spa',
    ],
    Elettronica: [
      'Power bank',
      'Caricabatterie multi',
      'Cavo unico',
      'Adattatore',
      'Auricolari',
      'Supporto telefono',
      'Caricabatterie auto',
      'Hub mini',
      'Batteria slim',
      'Caricabatterie wireless',
    ],
    Farmaci: [
      'Antidolorifico',
      'Cerotti',
      'Antiacido',
      'Antistaminico',
      'Disinfettante',
      'Integratore',
      'Collirio',
      'Melatonina',
      'Repellente',
      'Spray nasale',
    ],
    Accessori: [
      'Zaino da giorno',
      'Borraccia',
      'Ombrello',
      'Organizer valigia',
      'Lucchetto',
      'Beauty case',
      'Borsa pieghevole',
      'Portaoggetti',
      'Cintura portasoldi',
      'Sacca spesa',
    ],
    Extra: [
      'Libro',
      'Snack premium',
      'Giochi carte',
      'Thermos',
      'Carte',
      'Rivista',
      'Diario viaggio',
      'Playlist offline',
      'Giochi',
      'Snack',
    ],
    Bambini: [
      'Pigiama preferito',
      'Giocattolo unico',
      'Cambio completo',
      'Merenda',
      'Borraccia bimbo',
      'Giochi',
      'Felpa',
      'Scarpe',
      'Libro',
      'Thermos',
    ],
    Animali: [
      'Snack pet extra',
      'Giochi',
      'Coperta',
      'Ciotole',
      'Guinzaglio',
      'Tappetino',
      'Borsa',
      'Documenti pet',
      'Cibo',
      'Salviette',
    ],
  },
  famiglia: {
    Abbigliamento: [
      'Giacca impermeabile',
      'Pantalone elastico',
      'Scarpe chiuse',
      'Maglietta scura',
      'Polo',
      'Pantaloncini',
      'Sneaker',
      'Camicia',
      'Cappello',
      'Felpa',
    ],
    Igiene: [
      'Gel mani',
      'Deodorante',
      'Salviette disinfettanti',
      'Crema mani',
      'Shampoo travel',
      'Dentifricio travel',
      'Balsamo labbra',
      'Crema solare',
      'Spray igienizzante',
      'Sapone mani portatile',
    ],
    Documenti: [
      'Documenti bambini',
      'Libretto sanitario bambino',
      'Autorizzazione minori',
      'Tessera pediatra',
      'Lista farmaci bambino',
      'Documenti pet',
      'Passaporto pet',
      'Certificati vaccini bimbo',
      'Assicurazione famiglia',
      'Documenti seggiolino',
    ],
    Elettronica: [
      'Tablet bambini',
      'Caricabatterie multi',
      'Power bank',
      'Adattatore',
      'Cavo lungo',
      'Supporto tablet',
      'Auricolari bambini',
      'Caricabatterie wireless',
      'Batteria tablet',
      'Adattatore auto',
    ],
    Farmaci: [
      'Termometro',
      'Farmaci febbre bambini',
      'Soluzione nasale bambini',
      'Crema barriera',
      'Antistaminico bambini',
      'Farmaci cinetosi bambini',
      'Cerotti bambini',
      'Antipiretico bambini',
      'Integratore bambini',
      'Collirio bambini',
    ],
    Accessori: [
      'Borsa pannolini',
      'Borsa termica',
      'Organizer famiglia',
      'Borsa giocattoli',
      'Borsa spesa',
      'Lucchetto',
      'Portadocumenti',
      'Occhiali da sole',
      'Zaino da giorno',
      'Borraccia',
    ],
    Extra: [
      'Giochi viaggio',
      'Carte',
      'Puzzle tascabile',
      'Peluche',
      'Album colori',
      'Giochi auto',
      'Snack bambini',
      'Giocattolo preferito',
      'Snack pet',
      'Libro bambini',
    ],
    Bambini: [
      'Ciuccio',
      'Latte in polvere',
      'Bavaglino',
      'Passeggino',
      'Marsupio',
      'Fasciatoio portatile',
      'Set pappa',
      'Termos pappa',
      'Crema barriera',
      'Monitor neonato',
    ],
    Animali: [
      'Tappetino viaggio pet',
      'Ciotole pieghevoli',
      'Pettorina',
      'Cuccia portatile',
      'Gioco preferito',
      'Trasportino',
      'Museruola',
      'Spazzola pet',
      'Borsa cibo',
      'Salviette pet',
    ],
  },
} as const satisfies PackingTemplateCatalogMap;

export const PACKING_AI_CATALOG = [
  { name: 'Piumino packable', category: 'Abbigliamento', tags: ['montagna', 'freddo', 'weekend'], sort_order: 10 },
  { name: 'Giacca pesante', category: 'Abbigliamento', tags: ['montagna', 'freddo'], sort_order: 20 },
  { name: 'K-way', category: 'Abbigliamento', tags: ['pioggia', 'montagna'], sort_order: 30 },
  { name: 'Guanti pesanti', category: 'Abbigliamento', tags: ['freddo', 'montagna'], sort_order: 40 },
  { name: 'Sciarpa lana', category: 'Abbigliamento', tags: ['freddo', 'cultura'], sort_order: 50 },
  { name: 'Abbigliamento termico', category: 'Abbigliamento', tags: ['freddo', 'montagna'], sort_order: 60 },
  { name: 'Pantaloni impermeabili', category: 'Abbigliamento', tags: ['pioggia', 'montagna'], sort_order: 70 },
  { name: 'Stivali pioggia', category: 'Abbigliamento', tags: ['pioggia'], sort_order: 80 },
  { name: 'Vestito cerimonia', category: 'Abbigliamento', tags: ['business', 'cultura'], sort_order: 90 },
  { name: 'Cuffia nuoto', category: 'Abbigliamento', tags: ['mare', 'lago'], sort_order: 100 },
  { name: 'Muta leggera', category: 'Abbigliamento', tags: ['mare'], sort_order: 110 },
  { name: 'Camice antimoscerini', category: 'Abbigliamento', tags: ['montagna', 'lago'], sort_order: 120 },
  { name: 'Sandali trekking', category: 'Abbigliamento', tags: ['montagna'], sort_order: 130 },
  { name: 'Pantalone convertibile', category: 'Abbigliamento', tags: ['montagna', 'lago'], sort_order: 140 },
  { name: 'Abito cocktail', category: 'Abbigliamento', tags: ['business', 'weekend'], sort_order: 150 },
  { name: 'Slip mare', category: 'Abbigliamento', tags: ['mare', 'lago'], sort_order: 160 },
  { name: 'Reggiseno sportivo', category: 'Abbigliamento', tags: ['mare', 'montagna'], sort_order: 170 },
  { name: 'Softshell', category: 'Abbigliamento', tags: ['montagna'], sort_order: 180 },
  { name: 'Poncho', category: 'Abbigliamento', tags: ['pioggia'], sort_order: 190 },
  { name: 'Bandana', category: 'Abbigliamento', tags: ['mare', 'montagna', 'caldo'], sort_order: 200 },
  { name: 'Leggings', category: 'Abbigliamento', tags: ['weekend', 'cultura'], sort_order: 210 },
  { name: 'Overshirt', category: 'Abbigliamento', tags: ['cultura', 'weekend'], sort_order: 220 },
  { name: 'Fascia capelli', category: 'Abbigliamento', tags: ['mare', 'sport'], sort_order: 230 },
  { name: 'Ciabatte hotel', category: 'Abbigliamento', tags: ['business', 'lungo_raggio'], sort_order: 240 },
  { name: 'Maglione pesante', category: 'Abbigliamento', tags: ['freddo', 'weekend'], sort_order: 250 },
  { name: 'Rasoi', category: 'Igiene', tags: ['universal'], sort_order: 260 },
  { name: 'Fazzoletti', category: 'Igiene', tags: ['universal'], sort_order: 270 },
  { name: 'Flaconi silicone', category: 'Igiene', tags: ['lungo_raggio', 'volo'], sort_order: 280 },
  { name: 'Cotton fioc', category: 'Igiene', tags: ['universal'], sort_order: 290 },
  { name: 'Detergente intimo', category: 'Igiene', tags: ['universal'], sort_order: 300 },
  { name: 'Profumo solido', category: 'Igiene', tags: ['business', 'weekend'], sort_order: 310 },
  { name: 'Shampoo secco', category: 'Igiene', tags: ['weekend', 'business'], sort_order: 320 },
  { name: 'Maschera capelli', category: 'Igiene', tags: ['mare', 'lungo_raggio'], sort_order: 330 },
  { name: 'Filo interdentale', category: 'Igiene', tags: ['universal'], sort_order: 340 },
  { name: 'Collutorio travel', category: 'Igiene', tags: ['lungo_raggio'], sort_order: 350 },
  { name: 'Crema solare viso', category: 'Igiene', tags: ['mare', 'montagna'], sort_order: 360 },
  { name: 'Spazzolino elettrico', category: 'Igiene', tags: ['business', 'lungo_raggio'], sort_order: 370 },
  { name: 'Rasoi usa e getta', category: 'Igiene', tags: ['weekend'], sort_order: 380 },
  { name: 'Kit barba', category: 'Igiene', tags: ['business'], sort_order: 390 },
  { name: 'Crema antisfregamento', category: 'Igiene', tags: ['montagna', 'cultura'], sort_order: 400 },
  { name: 'Talco', category: 'Igiene', tags: ['caldo', 'mare'], sort_order: 410 },
  { name: 'Crema piedi', category: 'Igiene', tags: ['cultura', 'montagna'], sort_order: 420 },
  { name: 'Smaltoremover', category: 'Igiene', tags: ['weekend', 'lungo_raggio'], sort_order: 430 },
  { name: 'Salviette struccanti', category: 'Igiene', tags: ['business', 'weekend'], sort_order: 440 },
  { name: 'Deodorante crystal', category: 'Igiene', tags: ['universal'], sort_order: 450 },
  { name: 'Spugna viaggio', category: 'Igiene', tags: ['mare', 'lago'], sort_order: 460 },
  { name: 'Bagnoschiuma solido', category: 'Igiene', tags: ['lungo_raggio'], sort_order: 470 },
  { name: 'Gel doccia solido', category: 'Igiene', tags: ['lungo_raggio'], sort_order: 480 },
  { name: 'Patch acne', category: 'Igiene', tags: ['weekend'], sort_order: 490 },
  { name: 'Pettine tascabile', category: 'Igiene', tags: ['business', 'weekend'], sort_order: 500 },
  { name: 'Passaporto', category: 'Documenti', tags: ['volo', 'lungo_raggio'], sort_order: 510 },
  { name: 'Visto', category: 'Documenti', tags: ['volo', 'lungo_raggio'], sort_order: 520 },
  { name: 'Patente internazionale', category: 'Documenti', tags: ['lungo_raggio'], sort_order: 530 },
  { name: 'Green card', category: 'Documenti', tags: ['lungo_raggio'], sort_order: 540 },
  { name: 'Certificato vaccinazioni', category: 'Documenti', tags: ['volo', 'lungo_raggio'], sort_order: 550 },
  { name: 'Carta imbarco', category: 'Documenti', tags: ['volo'], sort_order: 560 },
  { name: 'Boarding pass backup', category: 'Documenti', tags: ['volo'], sort_order: 570 },
  { name: 'Traduzione documenti', category: 'Documenti', tags: ['lungo_raggio', 'business'], sort_order: 580 },
  { name: 'Procura', category: 'Documenti', tags: ['lungo_raggio'], sort_order: 590 },
  { name: 'Voucher noleggio auto', category: 'Documenti', tags: ['weekend', 'lungo_raggio'], sort_order: 600 },
  { name: 'Abbonamento metro', category: 'Documenti', tags: ['cultura', 'business'], sort_order: 610 },
  { name: 'QR musei backup', category: 'Documenti', tags: ['cultura'], sort_order: 620 },
  { name: 'Certificato medico sport', category: 'Documenti', tags: ['montagna', 'mare'], sort_order: 630 },
  { name: 'Lista farmaci tradotta', category: 'Documenti', tags: ['lungo_raggio'], sort_order: 640 },
  { name: 'Tessere fidelity', category: 'Documenti', tags: ['business', 'weekend'], sort_order: 650 },
  { name: 'Permesso soggiorno', category: 'Documenti', tags: ['lungo_raggio'], sort_order: 660 },
  { name: 'ESTA', category: 'Documenti', tags: ['volo'], sort_order: 670 },
  { name: 'Assicurazione estesa', category: 'Documenti', tags: ['lungo_raggio', 'montagna'], sort_order: 680 },
  { name: 'Copia passaporto', category: 'Documenti', tags: ['volo', 'lungo_raggio'], sort_order: 690 },
  { name: 'Licenza pesca internazionale', category: 'Documenti', tags: ['lago'], sort_order: 700 },
  { name: 'Documenti auto noleggio', category: 'Documenti', tags: ['weekend', 'lungo_raggio'], sort_order: 710 },
  { name: 'Carta imbarco pet', category: 'Documenti', tags: ['volo', 'pet'], sort_order: 720 },
  { name: 'Tessera europea assicurazione', category: 'Documenti', tags: ['lungo_raggio'], sort_order: 730 },
  { name: 'Permesso caccia', category: 'Documenti', tags: ['montagna', 'lago'], sort_order: 740 },
  { name: 'Documenti matrimonio', category: 'Documenti', tags: ['cultura', 'weekend'], sort_order: 750 },
  { name: 'AirTag', category: 'Elettronica', tags: ['volo', 'lungo_raggio'], sort_order: 760 },
  { name: 'Adattatore UK', category: 'Elettronica', tags: ['lungo_raggio', 'volo'], sort_order: 770 },
  { name: 'Adattatore US', category: 'Elettronica', tags: ['lungo_raggio', 'volo'], sort_order: 780 },
  { name: 'Multipresa compatta', category: 'Elettronica', tags: ['lungo_raggio', 'business'], sort_order: 790 },
  { name: 'SD card', category: 'Elettronica', tags: ['cultura', 'mare'], sort_order: 800 },
  { name: 'Obiettivo clip', category: 'Elettronica', tags: ['mare', 'cultura'], sort_order: 810 },
  { name: 'Drone mini', category: 'Elettronica', tags: ['mare', 'montagna'], sort_order: 820 },
  { name: 'Convertitore voltaggio', category: 'Elettronica', tags: ['lungo_raggio', 'volo'], sort_order: 830 },
  { name: 'Caricabatterie fotocamera', category: 'Elettronica', tags: ['cultura', 'mare'], sort_order: 840 },
  { name: 'Batterie AA ricaricabili', category: 'Elettronica', tags: ['montagna', 'lungo_raggio'], sort_order: 850 },
  { name: 'Splitter audio', category: 'Elettronica', tags: ['treno', 'volo'], sort_order: 860 },
  { name: 'Tastiera pieghevole', category: 'Elettronica', tags: ['business'], sort_order: 870 },
  { name: 'Stylus', category: 'Elettronica', tags: ['business'], sort_order: 880 },
  { name: 'Walkie talkie', category: 'Elettronica', tags: ['montagna', 'famiglia'], sort_order: 890 },
  { name: 'Lampada USB', category: 'Elettronica', tags: ['lungo_raggio'], sort_order: 900 },
  { name: 'Filtro privacy webcam', category: 'Elettronica', tags: ['business'], sort_order: 910 },
  { name: 'Proiettore pocket', category: 'Elettronica', tags: ['famiglia', 'weekend'], sort_order: 920 },
  { name: 'Caricabatterie orologio', category: 'Elettronica', tags: ['universal'], sort_order: 930 },
  { name: 'Banda fitness', category: 'Elettronica', tags: ['montagna', 'mare'], sort_order: 940 },
  { name: 'Tracker bagaglio', category: 'Elettronica', tags: ['volo', 'lungo_raggio'], sort_order: 950 },
  { name: 'Caricabatterie rapido', category: 'Elettronica', tags: ['universal'], sort_order: 960 },
  { name: 'Cuffie over-ear', category: 'Elettronica', tags: ['treno', 'volo'], sort_order: 970 },
  { name: 'Microfono lavalier', category: 'Elettronica', tags: ['business'], sort_order: 980 },
  { name: 'Scheda SIM backup', category: 'Elettronica', tags: ['lungo_raggio', 'volo'], sort_order: 990 },
  { name: 'Power bank slim', category: 'Elettronica', tags: ['weekend', 'business'], sort_order: 1000 },
  { name: 'Fermenti lattici', category: 'Farmaci', tags: ['farmacia', 'lungo_raggio'], sort_order: 1010 },
  { name: 'Garze sterili', category: 'Farmaci', tags: ['farmacia', 'montagna'], sort_order: 1020 },
  { name: 'Bendaggio elastico', category: 'Farmaci', tags: ['farmacia', 'montagna'], sort_order: 1030 },
  { name: 'Pinzette', category: 'Farmaci', tags: ['farmacia'], sort_order: 1040 },
  { name: 'Forbici mediche', category: 'Farmaci', tags: ['farmacia'], sort_order: 1050 },
  { name: 'Probiotici', category: 'Farmaci', tags: ['farmacia', 'lungo_raggio'], sort_order: 1060 },
  { name: 'Pomata herpes', category: 'Farmaci', tags: ['farmacia'], sort_order: 1070 },
  { name: 'Spray gola', category: 'Farmaci', tags: ['farmacia', 'freddo'], sort_order: 1080 },
  { name: 'Vitamina C', category: 'Farmaci', tags: ['farmacia', 'freddo'], sort_order: 1090 },
  { name: 'Antimalarico', category: 'Farmaci', tags: ['lungo_raggio'], sort_order: 1100 },
  { name: 'Cerotti vesciche grandi', category: 'Farmaci', tags: ['montagna', 'cultura'], sort_order: 1110 },
  { name: 'Gel scottature', category: 'Farmaci', tags: ['mare', 'caldo'], sort_order: 1120 },
  { name: 'Antipiretico', category: 'Farmaci', tags: ['farmacia', 'famiglia'], sort_order: 1130 },
  { name: 'Crema emorroidi', category: 'Farmaci', tags: ['farmacia'], sort_order: 1140 },
  { name: 'Antiviral', category: 'Farmaci', tags: ['farmacia'], sort_order: 1150 },
  { name: 'Pomata punture', category: 'Farmaci', tags: ['mare', 'lago'], sort_order: 1160 },
  { name: 'Sali reidratanti', category: 'Farmaci', tags: ['mare', 'caldo', 'montagna'], sort_order: 1170 },
  { name: 'Antibiotico topico', category: 'Farmaci', tags: ['farmacia'], sort_order: 1180 },
  { name: 'Ghiaccio spray', category: 'Farmaci', tags: ['montagna', 'sport'], sort_order: 1190 },
  { name: 'Repellente forte', category: 'Farmaci', tags: ['montagna', 'lago'], sort_order: 1200 },
  { name: 'Integratori minerali', category: 'Farmaci', tags: ['montagna', 'lungo_raggio'], sort_order: 1210 },
  { name: 'Antistaminico sedativo', category: 'Farmaci', tags: ['volo', 'farmacia'], sort_order: 1220 },
  { name: 'Crema scottature II grado', category: 'Farmaci', tags: ['mare'], sort_order: 1230 },
  { name: 'Garze', category: 'Farmaci', tags: ['farmacia'], sort_order: 1240 },
  { name: 'Kit pronto soccorso leggero', category: 'Farmaci', tags: ['montagna', 'famiglia'], sort_order: 1250 },
  { name: 'Packing cubes', category: 'Accessori', tags: ['lungo_raggio'], sort_order: 1260 },
  { name: 'Lucchetto TSA', category: 'Accessori', tags: ['volo', 'lungo_raggio'], sort_order: 1270 },
  { name: 'Etichette bagaglio', category: 'Accessori', tags: ['volo', 'lungo_raggio'], sort_order: 1280 },
  { name: 'Bilancia bagaglio', category: 'Accessori', tags: ['volo'], sort_order: 1290 },
  { name: 'Cintura portasoldi', category: 'Accessori', tags: ['cultura', 'lungo_raggio'], sort_order: 1300 },
  { name: 'Lucchetto cavo', category: 'Accessori', tags: ['lungo_raggio'], sort_order: 1310 },
  { name: 'Copri valigia', category: 'Accessori', tags: ['volo', 'lungo_raggio'], sort_order: 1320 },
  { name: 'Organizer scarpe', category: 'Accessori', tags: ['lungo_raggio', 'business'], sort_order: 1330 },
  { name: 'Sacchetti compressione', category: 'Accessori', tags: ['lungo_raggio', 'montagna'], sort_order: 1340 },
  { name: 'Gancio borsa', category: 'Accessori', tags: ['business', 'weekend'], sort_order: 1350 },
  { name: 'Custodia occhiali sole', category: 'Accessori', tags: ['mare', 'montagna'], sort_order: 1360 },
  { name: 'Porta passaporto RFID', category: 'Accessori', tags: ['volo', 'lungo_raggio'], sort_order: 1370 },
  { name: 'Cuscino viaggio', category: 'Accessori', tags: ['volo', 'treno'], sort_order: 1380 },
  { name: 'Mascherina occhi', category: 'Accessori', tags: ['volo', 'treno'], sort_order: 1390 },
  { name: 'Tappi orecchie', category: 'Accessori', tags: ['volo', 'treno', 'mare'], sort_order: 1400 },
  { name: 'Adattatore sedile aereo', category: 'Accessori', tags: ['volo'], sort_order: 1410 },
  { name: 'Ganci appendini', category: 'Accessori', tags: ['business', 'lungo_raggio'], sort_order: 1420 },
  { name: 'Elastici vestiti', category: 'Accessori', tags: ['lungo_raggio'], sort_order: 1430 },
  { name: 'Borsa frigo', category: 'Accessori', tags: ['mare', 'lago', 'famiglia'], sort_order: 1440 },
  { name: 'Moschettone', category: 'Accessori', tags: ['montagna'], sort_order: 1450 },
  { name: 'Clip multiuso', category: 'Accessori', tags: ['montagna', 'weekend'], sort_order: 1460 },
  { name: 'Occhiali da vista', category: 'Accessori', tags: ['universal'], sort_order: 1470 },
  { name: 'Portabottiglia', category: 'Accessori', tags: ['montagna', 'mare'], sort_order: 1480 },
  { name: 'Sacca spesa', category: 'Accessori', tags: ['cultura', 'weekend'], sort_order: 1490 },
  { name: 'Borsa a tracolla', category: 'Accessori', tags: ['cultura', 'weekend'], sort_order: 1500 },
  { name: 'Ventaglio', category: 'Extra', tags: ['caldo', 'cultura'], sort_order: 1510 },
  { name: 'Kit lavaggio panni', category: 'Extra', tags: ['lungo_raggio'], sort_order: 1520 },
  { name: 'Sacchetto panni sporchi', category: 'Extra', tags: ['lungo_raggio'], sort_order: 1530 },
  { name: 'Corda stendino', category: 'Extra', tags: ['lungo_raggio'], sort_order: 1540 },
  { name: 'Mollette', category: 'Extra', tags: ['lungo_raggio'], sort_order: 1550 },
  { name: 'Speaker bluetooth', category: 'Extra', tags: ['mare', 'weekend'], sort_order: 1560 },
  { name: 'Polaroid', category: 'Extra', tags: ['weekend', 'cultura'], sort_order: 1570 },
  { name: 'Coperta viaggio', category: 'Extra', tags: ['treno', 'volo'], sort_order: 1580 },
  { name: 'Cuscino gonfiabile', category: 'Extra', tags: ['volo', 'treno'], sort_order: 1590 },
  { name: 'Sedia pieghevole', category: 'Extra', tags: ['mare', 'lago'], sort_order: 1600 },
  { name: 'Ombrello grande', category: 'Extra', tags: ['pioggia', 'cultura'], sort_order: 1610 },
  { name: 'Kit cucina leggero', category: 'Extra', tags: ['montagna', 'lago'], sort_order: 1620 },
  { name: 'Posate travel', category: 'Extra', tags: ['lungo_raggio'], sort_order: 1630 },
  { name: 'Sacco liner', category: 'Extra', tags: ['montagna'], sort_order: 1640 },
  { name: 'Zaino idratazione', category: 'Extra', tags: ['montagna'], sort_order: 1650 },
  { name: 'Giornale viaggio', category: 'Extra', tags: ['weekend', 'cultura'], sort_order: 1660 },
  { name: 'Binocolo compatto', category: 'Extra', tags: ['montagna', 'lago'], sort_order: 1670 },
  { name: 'Drone', category: 'Extra', tags: ['mare', 'montagna'], sort_order: 1680 },
  { name: 'Carte speciali', category: 'Extra', tags: ['weekend', 'famiglia'], sort_order: 1690 },
  { name: 'Hamaca', category: 'Extra', tags: ['mare', 'lago'], sort_order: 1700 },
  { name: 'Thermos grande', category: 'Extra', tags: ['montagna', 'lungo_raggio'], sort_order: 1710 },
  { name: 'Candele travel', category: 'Extra', tags: ['weekend'], sort_order: 1720 },
  { name: 'Giochi da tavolo', category: 'Extra', tags: ['famiglia', 'weekend'], sort_order: 1730 },
  { name: 'Pallone', category: 'Extra', tags: ['mare', 'famiglia'], sort_order: 1740 },
  { name: 'Set picnic', category: 'Extra', tags: ['lago', 'weekend'], sort_order: 1750 },
  { name: 'Seggiolino auto', category: 'Bambini', tags: ['famiglia'], sort_order: 1760 },
  { name: 'Rialzo seggiolino', category: 'Bambini', tags: ['famiglia'], sort_order: 1770 },
  { name: 'Adattatore passeggino aereo', category: 'Bambini', tags: ['famiglia', 'volo'], sort_order: 1780 },
  { name: 'Sterilizzatore biberon', category: 'Bambini', tags: ['famiglia'], sort_order: 1790 },
  { name: 'Scaldabiberon', category: 'Bambini', tags: ['famiglia'], sort_order: 1800 },
  { name: 'Sacchetti pannolini', category: 'Bambini', tags: ['famiglia'], sort_order: 1810 },
  { name: 'Album adesivi', category: 'Bambini', tags: ['famiglia', 'weekend'], sort_order: 1820 },
  { name: 'Libri illustrati', category: 'Bambini', tags: ['famiglia', 'cultura'], sort_order: 1830 },
  { name: 'Zainetto autonomia', category: 'Bambini', tags: ['famiglia', 'cultura'], sort_order: 1840 },
  { name: 'Tutina extra', category: 'Bambini', tags: ['famiglia'], sort_order: 1850 },
  { name: 'Scarpine', category: 'Bambini', tags: ['famiglia'], sort_order: 1860 },
  { name: 'Porta pappa', category: 'Bambini', tags: ['famiglia'], sort_order: 1870 },
  { name: 'Tappetino cambio', category: 'Bambini', tags: ['famiglia'], sort_order: 1880 },
  { name: 'Baby monitor', category: 'Bambini', tags: ['famiglia'], sort_order: 1890 },
  { name: 'Zaino reins', category: 'Bambini', tags: ['famiglia', 'cultura'], sort_order: 1900 },
  { name: 'Bavaglino silicone', category: 'Bambini', tags: ['famiglia'], sort_order: 1910 },
  { name: 'Grembiule', category: 'Bambini', tags: ['famiglia'], sort_order: 1920 },
  { name: 'Giochi bagno', category: 'Bambini', tags: ['famiglia', 'mare'], sort_order: 1930 },
  { name: 'Pennarelli lavabili', category: 'Bambini', tags: ['famiglia', 'weekend'], sort_order: 1940 },
  { name: 'Pannolini notte', category: 'Bambini', tags: ['famiglia'], sort_order: 1950 },
  { name: 'Ciuccio ricambio', category: 'Bambini', tags: ['famiglia'], sort_order: 1960 },
  { name: 'Coperta sicurezza', category: 'Bambini', tags: ['famiglia'], sort_order: 1970 },
  { name: 'Nanna portatile', category: 'Bambini', tags: ['famiglia'], sort_order: 1980 },
  { name: 'Peluche ricambio', category: 'Bambini', tags: ['famiglia', 'weekend'], sort_order: 1990 },
  { name: 'Seggiolino bici', category: 'Bambini', tags: ['famiglia', 'weekend'], sort_order: 2000 },
  { name: 'Spazzola', category: 'Animali', tags: ['pet'], sort_order: 2010 },
  { name: 'Shampoo pet', category: 'Animali', tags: ['pet'], sort_order: 2020 },
  { name: 'Tagliaunghie', category: 'Animali', tags: ['pet'], sort_order: 2030 },
  { name: 'Farmaci pet abituali', category: 'Animali', tags: ['pet'], sort_order: 2040 },
  { name: 'Sedativo viaggio', category: 'Animali', tags: ['pet', 'volo'], sort_order: 2050 },
  { name: 'Carrier aereo omologato', category: 'Animali', tags: ['pet', 'volo'], sort_order: 2060 },
  { name: 'Tappetino assorbente', category: 'Animali', tags: ['pet'], sort_order: 2070 },
  { name: 'Cintura auto', category: 'Animali', tags: ['pet', 'famiglia'], sort_order: 2080 },
  { name: 'Barriera auto', category: 'Animali', tags: ['pet', 'famiglia'], sort_order: 2090 },
  { name: 'Collare LED', category: 'Animali', tags: ['pet', 'montagna'], sort_order: 2100 },
  { name: 'Cooling mat', category: 'Animali', tags: ['pet', 'caldo'], sort_order: 2110 },
  { name: 'Bottiglia portatile', category: 'Animali', tags: ['pet', 'mare'], sort_order: 2120 },
  { name: 'Snack dental', category: 'Animali', tags: ['pet'], sort_order: 2130 },
  { name: 'Felpa pet', category: 'Animali', tags: ['pet', 'freddo'], sort_order: 2140 },
  { name: 'GPS pet', category: 'Animali', tags: ['pet'], sort_order: 2150 },
  { name: 'Imbracatura trekking', category: 'Animali', tags: ['pet', 'montagna'], sort_order: 2160 },
  { name: 'Documenti pet UE', category: 'Animali', tags: ['pet', 'lungo_raggio'], sort_order: 2170 },
  { name: 'Gioco puzzle', category: 'Animali', tags: ['pet'], sort_order: 2180 },
  { name: 'Coperta riscaldante', category: 'Animali', tags: ['pet', 'freddo'], sort_order: 2190 },
  { name: 'Kit pronto soccorso', category: 'Animali', tags: ['pet'], sort_order: 2200 },
  { name: 'Guinzaglio retrattile', category: 'Animali', tags: ['pet', 'cultura'], sort_order: 2210 },
  { name: 'Ciotola antivoracità', category: 'Animali', tags: ['pet'], sort_order: 2220 },
  { name: 'Pettorina riflettente', category: 'Animali', tags: ['pet', 'montagna'], sort_order: 2230 },
  { name: 'Borsa trasporto', category: 'Animali', tags: ['pet', 'volo'], sort_order: 2240 },
  { name: 'Microchip', category: 'Animali', tags: ['pet', 'lungo_raggio'], sort_order: 2250 },
] as const satisfies readonly PackingAiCatalogEntry[];

/** Espande PACKING_STANDARD_CATALOG in righe con tier e sort_order per il DB. */
export function expandStandardCatalog(): PackingStandardCatalogItem[] {
  const rows: PackingStandardCatalogItem[] = [];
  let order = 10;
  for (const category of CATEGORY_ORDER) {
    const tier: PackingStandardItemTier =
      category === 'Bambini' || category === 'Animali' ? 'additional' : 'core';
    for (const name of PACKING_STANDARD_CATALOG[category]) {
      rows.push({ category, name, tier, sort_order: order });
      order += 10;
    }
  }
  return rows;
}

/** Valida il catalogo congelato in memoria. */
export function validatePackingDomainCatalog(): PackingDomainValidationReport {
  return validatePackingDomainCatalogData({
    standard: PACKING_STANDARD_CATALOG,
    template: PACKING_TEMPLATE_CATALOG,
    ai: PACKING_AI_CATALOG,
  });
}
