-- =============================================================================
-- MIGRATION: 20260623120000_suitcase_ai_modal_design_system_tokens.sql
-- DESCRIZIONE: Token Design System per modal Suggerimenti AI + retune titolo/header
-- SICUREZZA:   UPSERT su component_key — aggiorna righe esistenti, inserisce nuove.
-- =============================================================================

INSERT INTO public.design_system_rules (
    section,
    element_name,
    component_key,
    font_family,
    text_size,
    font_weight,
    text_transform,
    tracking,
    color_class,
    line_height,
    effect_class,
    css_class,
    preview_text
)
VALUES
    (
        'suitcase',
        'Titolo Modal AI',
        'suitcase_title',
        'font-display',
        'text-xl',
        'font-bold',
        'uppercase',
        'tracking-wide',
        'text-white',
        'leading-none',
        'none',
        NULL,
        'Suggerimenti AI'
    ),
    (
        'suitcase',
        'Label Sezioni / Header',
        'suitcase_label_caps',
        'font-sans',
        'text-[11px]',
        'font-black',
        'uppercase',
        'tracking-[0.2em]',
        'text-amber-500',
        'leading-none',
        'none',
        NULL,
        'CATEGORIE SELEZIONATE'
    ),
    (
        'suitcase',
        'Titolo Card Modalità AI',
        'suitcase_mode_card_title',
        'font-sans',
        'text-[14px]',
        'font-bold',
        'normal-case',
        'tracking-normal',
        NULL,
        'leading-snug',
        'none',
        NULL,
        'Valuta ed inserisci'
    ),
    (
        'suitcase',
        'Testo Empty State AI',
        'suitcase_empty_state',
        'font-sans',
        NULL,
        NULL,
        NULL,
        NULL,
        'text-slate-500',
        NULL,
        'none',
        'text-[12px] font-normal italic',
        'Nessuna categoria disponibile.'
    ),
    (
        'suitcase',
        'Testo Chip Categoria AI',
        'suitcase_category_chip',
        'font-sans',
        'text-[12.5px]',
        'font-bold',
        'normal-case',
        'tracking-normal',
        NULL,
        'leading-none',
        'none',
        NULL,
        'Abbigliamento'
    ),
    (
        'suitcase',
        'Titolo Modal AI (Mob)',
        'suitcase_title_mobile',
        'font-display',
        'text-lg',
        'font-bold',
        'uppercase',
        'tracking-wide',
        'text-white',
        'leading-none',
        'none',
        NULL,
        'Suggerimenti AI'
    ),
    (
        'suitcase',
        'Label Sezioni (Mob)',
        'suitcase_label_caps_mobile',
        'font-sans',
        'text-[11px]',
        'font-black',
        'uppercase',
        'tracking-[0.2em]',
        'text-amber-500',
        'leading-none',
        'none',
        NULL,
        'CATEGORIE SELEZIONATE'
    ),
    (
        'suitcase',
        'Titolo Card Modalità AI (Mob)',
        'suitcase_mode_card_title_mobile',
        'font-sans',
        'text-[14px]',
        'font-bold',
        'normal-case',
        'tracking-normal',
        NULL,
        'leading-snug',
        'none',
        NULL,
        'Valuta ed inserisci'
    ),
    (
        'suitcase',
        'Testo Empty State AI (Mob)',
        'suitcase_empty_state_mobile',
        'font-sans',
        NULL,
        NULL,
        NULL,
        NULL,
        'text-slate-500',
        NULL,
        'none',
        'text-[12px] font-normal italic',
        'Nessuna categoria disponibile.'
    ),
    (
        'suitcase',
        'Testo Chip Categoria AI (Mob)',
        'suitcase_category_chip_mobile',
        'font-sans',
        'text-[12.5px]',
        'font-bold',
        'normal-case',
        'tracking-normal',
        NULL,
        'leading-none',
        'none',
        NULL,
        'Abbigliamento'
    )
ON CONFLICT (component_key) DO UPDATE SET
    section = EXCLUDED.section,
    element_name = EXCLUDED.element_name,
    font_family = EXCLUDED.font_family,
    text_size = EXCLUDED.text_size,
    font_weight = EXCLUDED.font_weight,
    text_transform = EXCLUDED.text_transform,
    tracking = EXCLUDED.tracking,
    color_class = EXCLUDED.color_class,
    line_height = EXCLUDED.line_height,
    effect_class = EXCLUDED.effect_class,
    css_class = EXCLUDED.css_class,
    preview_text = EXCLUDED.preview_text,
    updated_at = now();
