-- Macrofase C: allinea packing_template_items al catalogo congelato
-- Sostituisce gli item specifici per ogni template TD (non tocca valigie utente)


-- Template: Template Mare
DELETE FROM public.packing_template_items
WHERE template_id IN (
  SELECT id FROM public.suitcases WHERE user_id IS NULL AND title ILIKE 'Template Mare'
);

INSERT INTO public.packing_template_items (template_id, category, name, sort_order, is_active)
SELECT s.id, v.category, v.name, v.sort_order, true
FROM public.suitcases s
CROSS JOIN (
  VALUES
    ('Abbigliamento', 'Costume', 10),
    ('Abbigliamento', 'Infradito', 20),
    ('Abbigliamento', 'Shorts', 30),
    ('Abbigliamento', 'Sandali', 40),
    ('Abbigliamento', 'Copricostume', 50),
    ('Abbigliamento', 'Maglietta UV', 60),
    ('Abbigliamento', 'Bermuda', 70),
    ('Abbigliamento', 'Canotta estiva', 80),
    ('Abbigliamento', 'Cappello sole', 90),
    ('Abbigliamento', 'Camicia leggera estiva', 100),
    ('Igiene', 'Crema solare', 10),
    ('Igiene', 'Doposole', 20),
    ('Igiene', 'Shampoo antisale', 30),
    ('Igiene', 'Balsamo capelli', 40),
    ('Igiene', 'Gel doccia', 50),
    ('Igiene', 'Salviette corpo', 60),
    ('Igiene', 'Detergente viso', 70),
    ('Igiene', 'After-sun capelli', 80),
    ('Igiene', 'Accappatoio', 90),
    ('Igiene', 'Asciugamano microfibra', 100),
    ('Documenti', 'Prenotazione spiaggia', 10),
    ('Documenti', 'Voucher attività mare', 20),
    ('Documenti', 'Polizza sport acquatici', 30),
    ('Documenti', 'Prenotazione diving', 40),
    ('Documenti', 'Mappa costa', 50),
    ('Documenti', 'Tessera club nautico', 60),
    ('Documenti', 'Assicurazione annullamento', 70),
    ('Documenti', 'Permesso barca', 80),
    ('Documenti', 'Documenti minori', 90),
    ('Documenti', 'Voucher noleggio', 100),
    ('Elettronica', 'Custodia impermeabile', 10),
    ('Elettronica', 'Action cam', 20),
    ('Elettronica', 'Caricatore solare', 30),
    ('Elettronica', 'Power bank', 40),
    ('Elettronica', 'Adattatore auto', 50),
    ('Elettronica', 'Supporto telefono', 60),
    ('Elettronica', 'Cavo lungo', 70),
    ('Elettronica', 'Speaker compatto', 80),
    ('Elettronica', 'Luce notturna', 90),
    ('Elettronica', 'Asciugacapelli mini', 100),
    ('Farmaci', 'Crema punture medusa', 10),
    ('Farmaci', 'Antistaminico', 20),
    ('Farmaci', 'Soluzione fisiologica', 30),
    ('Farmaci', 'Cerotti ampolla', 40),
    ('Farmaci', 'Integratore sali', 50),
    ('Farmaci', 'Collirio', 60),
    ('Farmaci', 'Antinfiammatorio', 70),
    ('Farmaci', 'Gel post-ustione', 80),
    ('Farmaci', 'Pomata antibiotica topica', 90),
    ('Farmaci', 'Spray raffreddamento', 100),
    ('Accessori', 'Borsa mare', 10),
    ('Accessori', 'Sacca impermeabile', 20),
    ('Accessori', 'Occhiali da sole', 30),
    ('Accessori', 'Telo zaino spiaggia', 40),
    ('Accessori', 'Cappello cordino', 50),
    ('Accessori', 'Tappi orecchie nuoto', 60),
    ('Accessori', 'Custodia occhiali', 70),
    ('Accessori', 'Borsa rete', 80),
    ('Accessori', 'Zaino da giorno', 90),
    ('Accessori', 'Borraccia', 100),
    ('Extra', 'Telo mare', 10),
    ('Extra', 'Maschera e boccaglio', 20),
    ('Extra', 'Pallone spiaggia', 30),
    ('Extra', 'Giochi spiaggia', 40),
    ('Extra', 'Frisbee', 50),
    ('Extra', 'Secchiello bambini', 60),
    ('Extra', 'Ciambella nuoto', 70),
    ('Extra', 'Asciugamano mare', 80),
    ('Extra', 'Libro', 90),
    ('Extra', 'Speaker compatto', 100),
    ('Bambini', 'Costume bambino', 10),
    ('Bambini', 'Cappello bambino SPF', 20),
    ('Bambini', 'Scarpe acqua', 30),
    ('Bambini', 'Giochi sabbia', 40),
    ('Bambini', 'Salvagente', 50),
    ('Bambini', 'Crema solare bambini', 60),
    ('Bambini', 'Copricostume bimbo', 70),
    ('Bambini', 'T-shirt ricambio', 80),
    ('Bambini', 'Pantaloncini', 90),
    ('Bambini', 'Occhiali bimbo', 100),
    ('Animali', 'Asciugamano pet', 10),
    ('Animali', 'Acqua fresca pet', 20),
    ('Animali', 'Giubbottino', 30),
    ('Animali', 'Paw balm', 40),
    ('Animali', 'Telo auto', 50),
    ('Animali', 'Giochi', 60),
    ('Animali', 'Salviette pet', 70),
    ('Animali', 'Trasportino', 80),
    ('Animali', 'Coperta pet', 90),
    ('Animali', 'Ombra pet', 100)
) AS v(category, name, sort_order)
WHERE s.user_id IS NULL AND s.title ILIKE 'Template Mare'
ON CONFLICT (template_id, category, name) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();

-- Template: Template Fiumi & Laghi
DELETE FROM public.packing_template_items
WHERE template_id IN (
  SELECT id FROM public.suitcases WHERE user_id IS NULL AND title ILIKE 'Template Fiumi & Laghi'
);

INSERT INTO public.packing_template_items (template_id, category, name, sort_order, is_active)
SELECT s.id, v.category, v.name, v.sort_order, true
FROM public.suitcases s
CROSS JOIN (
  VALUES
    ('Abbigliamento', 'Costume', 10),
    ('Abbigliamento', 'Infradito', 20),
    ('Abbigliamento', 'Shorts', 30),
    ('Abbigliamento', 'Sandali', 40),
    ('Abbigliamento', 'Ciabatte', 50),
    ('Abbigliamento', 'T-shirt leggera', 60),
    ('Abbigliamento', 'Pantalone leggero', 70),
    ('Abbigliamento', 'Canotta', 80),
    ('Abbigliamento', 'Cappello sole', 90),
    ('Abbigliamento', 'Felpa', 100),
    ('Igiene', 'Crema solare', 10),
    ('Igiene', 'Doposole', 20),
    ('Igiene', 'Shampoo delicato', 30),
    ('Igiene', 'Balsamo labbra SPF', 40),
    ('Igiene', 'Gel doccia', 50),
    ('Igiene', 'Salviette', 60),
    ('Igiene', 'Detergente viso', 70),
    ('Igiene', 'Crema mani', 80),
    ('Igiene', 'Deodorante ricarica', 90),
    ('Igiene', 'Asciugamano microfibra', 100),
    ('Documenti', 'Permesso pesca', 10),
    ('Documenti', 'Mappa sentieri', 20),
    ('Documenti', 'Prenotazione traghetti', 30),
    ('Documenti', 'Voucher barca', 40),
    ('Documenti', 'Guida area', 50),
    ('Documenti', 'Biglietti escursioni', 60),
    ('Documenti', 'Assicurazione sport', 70),
    ('Documenti', 'Mappa lago', 80),
    ('Documenti', 'Documenti pet area', 90),
    ('Documenti', 'Prenotazione escursione', 100),
    ('Elettronica', 'Custodia impermeabile', 10),
    ('Elettronica', 'Fotocamera compatta', 20),
    ('Elettronica', 'Power bank', 30),
    ('Elettronica', 'Caricabatterie auto', 40),
    ('Elettronica', 'Supporto telefono', 50),
    ('Elettronica', 'Cavo lungo', 60),
    ('Elettronica', 'Luce frontale', 70),
    ('Elettronica', 'Adattatore', 80),
    ('Elettronica', 'Batteria ricambio', 90),
    ('Elettronica', 'Speaker compatto', 100),
    ('Farmaci', 'Repellente insetti', 10),
    ('Farmaci', 'Pomata post-puntura', 20),
    ('Farmaci', 'Antistaminico', 30),
    ('Farmaci', 'Antinfiammatorio', 40),
    ('Farmaci', 'Cerotti', 50),
    ('Farmaci', 'Crema antifungina', 60),
    ('Farmaci', 'Gel muscolare', 70),
    ('Farmaci', 'Disinfettante', 80),
    ('Farmaci', 'Collirio', 90),
    ('Farmaci', 'Integratore', 100),
    ('Accessori', 'Zaino da giorno', 10),
    ('Accessori', 'Sacca stagna', 20),
    ('Accessori', 'Borraccia', 30),
    ('Accessori', 'Occhiali da sole', 40),
    ('Accessori', 'Telo picnic', 50),
    ('Accessori', 'Cappello sole', 60),
    ('Accessori', 'Custodia documenti', 70),
    ('Accessori', 'Borsa frigo', 80),
    ('Accessori', 'Custodia impermeabile', 90),
    ('Accessori', 'Organizer valigia', 100),
    ('Extra', 'Telo picnic', 10),
    ('Extra', 'Giochi acqua', 20),
    ('Extra', 'Binocolo', 30),
    ('Extra', 'Thermos', 40),
    ('Extra', 'Libro', 50),
    ('Extra', 'Carte giochi', 60),
    ('Extra', 'Mappa area', 70),
    ('Extra', 'Giochi outdoor', 80),
    ('Extra', 'Amaca leggera', 90),
    ('Extra', 'Snack energetici', 100),
    ('Bambini', 'Costume bambino', 10),
    ('Bambini', 'Scarpe acqua', 20),
    ('Bambini', 'Giochi acqua', 30),
    ('Bambini', 'Cappello bimbo', 40),
    ('Bambini', 'T-shirt ricambio', 50),
    ('Bambini', 'Pantaloncini', 60),
    ('Bambini', 'Salvagente', 70),
    ('Bambini', 'Crema solare bambini', 80),
    ('Bambini', 'Coperta leggera', 90),
    ('Bambini', 'Giubbino', 100),
    ('Animali', 'Giubbottino galleggiante', 10),
    ('Animali', 'Telo auto', 20),
    ('Animali', 'Giochi acqua', 30),
    ('Animali', 'Borraccia pet', 40),
    ('Animali', 'Coperta pet', 50),
    ('Animali', 'Trasportino', 60),
    ('Animali', 'Ciotole pieghevoli', 70),
    ('Animali', 'Giochi', 80),
    ('Animali', 'Salviette pet', 90),
    ('Animali', 'Zampa protection', 100)
) AS v(category, name, sort_order)
WHERE s.user_id IS NULL AND s.title ILIKE 'Template Fiumi & Laghi'
ON CONFLICT (template_id, category, name) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();

-- Template: Template Montagna
DELETE FROM public.packing_template_items
WHERE template_id IN (
  SELECT id FROM public.suitcases WHERE user_id IS NULL AND title ILIKE 'Template Montagna'
);

INSERT INTO public.packing_template_items (template_id, category, name, sort_order, is_active)
SELECT s.id, v.category, v.name, v.sort_order, true
FROM public.suitcases s
CROSS JOIN (
  VALUES
    ('Abbigliamento', 'Scarponi trekking', 10),
    ('Abbigliamento', 'Pile', 20),
    ('Abbigliamento', 'Giacca antivento', 30),
    ('Abbigliamento', 'Giacca impermeabile', 40),
    ('Abbigliamento', 'Pantalone trekking', 50),
    ('Abbigliamento', 'Calze tecniche', 60),
    ('Abbigliamento', 'Buff', 70),
    ('Abbigliamento', 'Guanti', 80),
    ('Abbigliamento', 'Berretto', 90),
    ('Abbigliamento', 'Maglia termica', 100),
    ('Igiene', 'Crema protezione alta', 10),
    ('Igiene', 'Burrocacao', 20),
    ('Igiene', 'Crema mani riparatrice', 30),
    ('Igiene', 'Detergente delicato', 40),
    ('Igiene', 'Balsamo labbra', 50),
    ('Igiene', 'Sapone solido', 60),
    ('Igiene', 'Crema viso barriera', 70),
    ('Igiene', 'Idratante intenso', 80),
    ('Igiene', 'Gel doccia montagna', 90),
    ('Igiene', 'Asciugamano microfibra', 100),
    ('Documenti', 'Carta sentieri', 10),
    ('Documenti', 'Permesso parco', 20),
    ('Documenti', 'Mappa trekking', 30),
    ('Documenti', 'Assicurazione SAR', 40),
    ('Documenti', 'Licenza rifugio', 50),
    ('Documenti', 'Prenotazione guide', 60),
    ('Documenti', 'Bollettino meteo', 70),
    ('Documenti', 'Registro rifugio', 80),
    ('Documenti', 'Permesso arrampicata', 90),
    ('Elettronica', 'Frontale', 10),
    ('Elettronica', 'Power bank', 20),
    ('Elettronica', 'GPS esterno', 30),
    ('Elettronica', 'Batteria frontale', 40),
    ('Elettronica', 'Cavo lungo', 50),
    ('Elettronica', 'Action cam', 60),
    ('Elettronica', 'Radio', 70),
    ('Elettronica', 'Termometro elettronico', 80),
    ('Elettronica', 'Caricabatterie robusto', 90),
    ('Elettronica', 'Batteria esterna camera', 100),
    ('Farmaci', 'Farmaci mal di montagna', 10),
    ('Farmaci', 'Cerotti vesciche', 20),
    ('Farmaci', 'Gel muscolare', 30),
    ('Farmaci', 'Integratori sali', 40),
    ('Farmaci', 'Antistaminico', 50),
    ('Farmaci', 'Benda elastica', 60),
    ('Farmaci', 'Antidolorifico forte', 70),
    ('Farmaci', 'Pomata articolazioni', 80),
    ('Farmaci', 'Crema labbra medicata', 90),
    ('Farmaci', 'Antinfiammatorio', 100),
    ('Accessori', 'Bastoncini trekking', 10),
    ('Accessori', 'Borraccia termica', 20),
    ('Accessori', 'Coprizaino', 30),
    ('Accessori', 'Fischietto', 40),
    ('Accessori', 'Cartella mappe', 50),
    ('Accessori', 'Moschettoni', 60),
    ('Accessori', 'Dry bag', 70),
    ('Accessori', 'Imbracatura leggera', 80),
    ('Accessori', 'Zaino da giorno', 90),
    ('Accessori', 'Borraccia', 100),
    ('Extra', 'Coltellino', 10),
    ('Extra', 'Binocolo', 20),
    ('Extra', 'Carta e penna', 30),
    ('Extra', 'Fodera sacco', 40),
    ('Extra', 'Filtro acqua', 50),
    ('Extra', 'Fischietto', 60),
    ('Extra', 'Sacca compressione', 70),
    ('Extra', 'Thermos', 80),
    ('Extra', 'Corda leggera', 90),
    ('Extra', 'Kit corda', 100),
    ('Bambini', 'Zaino bimbo', 10),
    ('Bambini', 'Felpa bimbo', 20),
    ('Bambini', 'Guanti bimbo', 30),
    ('Bambini', 'Pantalone trekking bimbo', 40),
    ('Bambini', 'Giacca impermeabile bimbo', 50),
    ('Bambini', 'Berretto bimbo', 60),
    ('Bambini', 'Calze ricambio', 70),
    ('Bambini', 'Termico bimbo', 80),
    ('Bambini', 'Scarpe chiuse', 90),
    ('Bambini', 'Buff bimbo', 100),
    ('Animali', 'Scarpette zampine', 10),
    ('Animali', 'Gilet riflettente', 20),
    ('Animali', 'Borraccia pet', 30),
    ('Animali', 'Kit pronto soccorso pet', 40),
    ('Animali', 'Imbracatura', 50),
    ('Animali', 'Coperta', 60),
    ('Animali', 'Giochi', 70),
    ('Animali', 'Salviette pet', 80),
    ('Animali', 'Guinzaglio', 90),
    ('Animali', 'Pettorina', 100)
) AS v(category, name, sort_order)
WHERE s.user_id IS NULL AND s.title ILIKE 'Template Montagna'
ON CONFLICT (template_id, category, name) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();

-- Template: Template Cultura
DELETE FROM public.packing_template_items
WHERE template_id IN (
  SELECT id FROM public.suitcases WHERE user_id IS NULL AND title ILIKE 'Template Cultura'
);

INSERT INTO public.packing_template_items (template_id, category, name, sort_order, is_active)
SELECT s.id, v.category, v.name, v.sort_order, true
FROM public.suitcases s
CROSS JOIN (
  VALUES
    ('Abbigliamento', 'Scarpe da passeggiata', 10),
    ('Abbigliamento', 'Pantaloni comodi', 20),
    ('Abbigliamento', 'Polo', 30),
    ('Abbigliamento', 'Cardigan', 40),
    ('Abbigliamento', 'Sciarpa leggera', 50),
    ('Abbigliamento', 'Sneaker', 60),
    ('Abbigliamento', 'Pantalone leggero', 70),
    ('Abbigliamento', 'Blazer casual', 80),
    ('Abbigliamento', 'Gonna o vestito', 90),
    ('Abbigliamento', 'Camicia casual', 100),
    ('Igiene', 'Gel mani', 10),
    ('Igiene', 'Salviette igienizzanti', 20),
    ('Igiene', 'Deodorante travel', 30),
    ('Igiene', 'Crema mani', 40),
    ('Igiene', 'Schiuma da barba', 50),
    ('Igiene', 'Balsamo barba', 60),
    ('Igiene', 'Kit manicure', 70),
    ('Igiene', 'Profumo leggero', 80),
    ('Igiene', 'Dischetti struccanti', 90),
    ('Igiene', 'Spray igienizzante', 100),
    ('Documenti', 'Biglietti musei', 10),
    ('Documenti', 'City pass', 20),
    ('Documenti', 'Mappa offline', 30),
    ('Documenti', 'Audioguida', 40),
    ('Documenti', 'Prenotazioni ristorante', 50),
    ('Documenti', 'Biglietti teatro', 60),
    ('Documenti', 'Abbonamento trasporti', 70),
    ('Documenti', 'Prenotazione tour', 80),
    ('Documenti', 'Guida turistica', 90),
    ('Documenti', 'Lista orari monumenti', 100),
    ('Elettronica', 'E-reader', 10),
    ('Elettronica', 'Fotocamera compatta', 20),
    ('Elettronica', 'Power bank', 30),
    ('Elettronica', 'Adattatore audio guida', 40),
    ('Elettronica', 'Cavo lungo', 50),
    ('Elettronica', 'Caricabatterie foto', 60),
    ('Elettronica', 'Hard disk portatile', 70),
    ('Elettronica', 'Mouse pieghevole', 80),
    ('Elettronica', 'Selfie stick', 90),
    ('Elettronica', 'Hub USB', 100),
    ('Farmaci', 'Cerotti vesciche', 10),
    ('Farmaci', 'Antistaminico', 20),
    ('Farmaci', 'Antinfiammatorio', 30),
    ('Farmaci', 'Integratore', 40),
    ('Farmaci', 'Disinfettante', 50),
    ('Farmaci', 'Antiacido', 60),
    ('Farmaci', 'Spray nasale', 70),
    ('Farmaci', 'Melatonina', 80),
    ('Farmaci', 'Antidolorifico', 90),
    ('Farmaci', 'Collirio', 100),
    ('Accessori', 'Zaino da giorno', 10),
    ('Accessori', 'Portafoglio RFID', 20),
    ('Accessori', 'Borsa crossbody', 30),
    ('Accessori', 'Ombrello', 40),
    ('Accessori', 'Portadocumenti', 50),
    ('Accessori', 'Cintura portasoldi', 60),
    ('Accessori', 'Occhiali da sole', 70),
    ('Accessori', 'Borsa pieghevole', 80),
    ('Accessori', 'Organizer cavi', 90),
    ('Accessori', 'Beauty case', 100),
    ('Extra', 'Taccuino', 10),
    ('Extra', 'Penna', 20),
    ('Extra', 'Borsa shopping', 30),
    ('Extra', 'Snack energetici', 40),
    ('Extra', 'Mappa cartacea', 50),
    ('Extra', 'Giochi viaggio', 60),
    ('Extra', 'Carte', 70),
    ('Extra', 'Libro', 80),
    ('Extra', 'Rivista', 90),
    ('Extra', 'Diario viaggio', 100),
    ('Bambini', 'Zaino bimbo', 10),
    ('Bambini', 'Snack lunghi', 20),
    ('Bambini', 'Giochi quiet', 30),
    ('Bambini', 'Libro bambini', 40),
    ('Bambini', 'Penna colori', 50),
    ('Bambini', 'Merenda', 60),
    ('Bambini', 'Acqua bimbo', 70),
    ('Bambini', 'Giochi magnetici', 80),
    ('Bambini', 'Auricolari limitati', 90),
    ('Bambini', 'Documenti tasca', 100),
    ('Animali', 'Borsa pet urbano', 10),
    ('Animali', 'Pettorina', 20),
    ('Animali', 'Salviette pet', 30),
    ('Animali', 'Giochi quiet', 40),
    ('Animali', 'Trasportino', 50),
    ('Animali', 'Cibo porzionato', 60),
    ('Animali', 'Giochi', 70),
    ('Animali', 'Ciotole', 80),
    ('Animali', 'Borraccia pet', 90),
    ('Animali', 'Documenti pet', 100)
) AS v(category, name, sort_order)
WHERE s.user_id IS NULL AND s.title ILIKE 'Template Cultura'
ON CONFLICT (template_id, category, name) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();

-- Template: Template Business
DELETE FROM public.packing_template_items
WHERE template_id IN (
  SELECT id FROM public.suitcases WHERE user_id IS NULL AND title ILIKE 'Template Business'
);

INSERT INTO public.packing_template_items (template_id, category, name, sort_order, is_active)
SELECT s.id, v.category, v.name, v.sort_order, true
FROM public.suitcases s
CROSS JOIN (
  VALUES
    ('Abbigliamento', 'Camicia elegante', 10),
    ('Abbigliamento', 'Pantalone elegante', 20),
    ('Abbigliamento', 'Blazer', 30),
    ('Abbigliamento', 'Scarpe eleganti', 40),
    ('Abbigliamento', 'Cravatta', 50),
    ('Abbigliamento', 'Calze eleganti', 60),
    ('Abbigliamento', 'Canottiera', 70),
    ('Abbigliamento', 'Giacca completo', 80),
    ('Abbigliamento', 'Abito serata', 90),
    ('Abbigliamento', 'Pantalone serata', 100),
    ('Igiene', 'Deodorante long-lasting', 10),
    ('Igiene', 'Crema mani non unta', 20),
    ('Igiene', 'Schiuma da barba', 30),
    ('Igiene', 'Balsamo barba', 40),
    ('Igiene', 'Kit manicure', 50),
    ('Igiene', 'Profumo leggero', 60),
    ('Igiene', 'Crema viso', 70),
    ('Igiene', 'Limatura unghie', 80),
    ('Igiene', 'Salviette', 90),
    ('Igiene', 'Deodorante ricarica', 100),
    ('Documenti', 'Biglietti da visita', 10),
    ('Documenti', 'Agenda', 20),
    ('Documenti', 'Badge evento', 30),
    ('Documenti', 'Contratti', 40),
    ('Documenti', 'Itinerario voli', 50),
    ('Documenti', 'Prenotazione hotel', 60),
    ('Documenti', 'Biglietti treno', 70),
    ('Documenti', 'Biglietti aereo', 80),
    ('Elettronica', 'Laptop', 10),
    ('Elettronica', 'Caricabatterie laptop', 20),
    ('Elettronica', 'Mouse wireless', 30),
    ('Elettronica', 'Hub USB-C', 40),
    ('Elettronica', 'Adattatore HDMI', 50),
    ('Elettronica', 'Pendrive', 60),
    ('Elettronica', 'Webcam', 70),
    ('Elettronica', 'Microfono cuffia', 80),
    ('Elettronica', 'Hard disk esterno', 90),
    ('Elettronica', 'Docking travel', 100),
    ('Farmaci', 'Farmaci cinetosi', 10),
    ('Farmaci', 'Antistaminico non sedante', 20),
    ('Farmaci', 'Antiacido', 30),
    ('Farmaci', 'Integratore', 40),
    ('Farmaci', 'Cerotti', 50),
    ('Farmaci', 'Collirio', 60),
    ('Farmaci', 'Antinfiammatorio', 70),
    ('Farmaci', 'Melatonina', 80),
    ('Farmaci', 'Spray nasale', 90),
    ('Farmaci', 'Antidolorifico', 100),
    ('Accessori', 'Borsa laptop', 10),
    ('Accessori', 'Organizer cavi', 20),
    ('Accessori', 'Portadocumenti', 30),
    ('Accessori', 'Portabadge', 40),
    ('Accessori', 'Lucchetto TSA', 50),
    ('Accessori', 'Borsa elegante', 60),
    ('Accessori', 'Astuccio penne', 70),
    ('Accessori', 'Custodia abiti', 80),
    ('Accessori', 'Zaino da giorno', 90),
    ('Accessori', 'Borraccia', 100),
    ('Extra', 'Blocco note', 10),
    ('Extra', 'Penne', 20),
    ('Extra', 'Snack meeting', 30),
    ('Extra', 'Thermos', 40),
    ('Extra', 'Rivista', 50),
    ('Extra', 'Caramelle', 60),
    ('Extra', 'Carta appunti', 70),
    ('Extra', 'Taccuino', 80),
    ('Extra', 'Snack', 90),
    ('Extra', 'Libro', 100),
    ('Bambini', 'Snack silenziosi', 10),
    ('Bambini', 'Giochi auto', 20),
    ('Bambini', 'Auricolari bimbo', 30),
    ('Bambini', 'Peluche', 40),
    ('Bambini', 'Cambio outfit', 50),
    ('Bambini', 'Libro', 60),
    ('Bambini', 'Giochi', 70),
    ('Bambini', 'Merenda', 80),
    ('Bambini', 'Borraccia bimbo', 90),
    ('Bambini', 'Tablet contenuto', 100),
    ('Animali', 'Ciotole', 10),
    ('Animali', 'Tappetino', 20),
    ('Animali', 'Salviette', 30),
    ('Animali', 'Giochi', 40),
    ('Animali', 'Borsa pet', 50),
    ('Animali', 'Cibo porzionato', 60),
    ('Animali', 'Guinzaglio', 70),
    ('Animali', 'Pettorina', 80),
    ('Animali', 'Borraccia pet', 90),
    ('Animali', 'Trasportino', 100)
) AS v(category, name, sort_order)
WHERE s.user_id IS NULL AND s.title ILIKE 'Template Business'
ON CONFLICT (template_id, category, name) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();

-- Template: Template Weekend
DELETE FROM public.packing_template_items
WHERE template_id IN (
  SELECT id FROM public.suitcases WHERE user_id IS NULL AND title ILIKE 'Template Weekend'
);

INSERT INTO public.packing_template_items (template_id, category, name, sort_order, is_active)
SELECT s.id, v.category, v.name, v.sort_order, true
FROM public.suitcases s
CROSS JOIN (
  VALUES
    ('Abbigliamento', 'Pantaloncini', 10),
    ('Abbigliamento', 'Polo', 20),
    ('Abbigliamento', 'Jeans', 30),
    ('Abbigliamento', 'Sneaker', 40),
    ('Abbigliamento', 'Outfit serata', 50),
    ('Abbigliamento', 'Felpa', 60),
    ('Abbigliamento', 'Maglione leggero', 70),
    ('Abbigliamento', 'Cappello', 80),
    ('Abbigliamento', 'Sciarpa leggera', 90),
    ('Abbigliamento', 'Giacca packable', 100),
    ('Igiene', 'Kit igiene travel size', 10),
    ('Igiene', 'Deodorante mini', 20),
    ('Igiene', 'Shampoo mini', 30),
    ('Igiene', 'Dentifricio mini', 40),
    ('Igiene', 'Sapone solido', 50),
    ('Igiene', 'Balsamo labbra', 60),
    ('Igiene', 'Gel doccia mini', 70),
    ('Igiene', 'Salviette', 80),
    ('Igiene', 'Spazzolino ricambio', 90),
    ('Igiene', 'Crema mani mini', 100),
    ('Documenti', 'Prenotazione ristorante', 10),
    ('Documenti', 'Biglietto evento', 20),
    ('Documenti', 'Prenotazione hotel', 30),
    ('Documenti', 'Mappa quartiere', 40),
    ('Documenti', 'Voucher esperienza', 50),
    ('Documenti', 'Conferma transfer', 60),
    ('Documenti', 'Biglietto concerto', 70),
    ('Documenti', 'Documenti noleggio auto', 80),
    ('Documenti', 'Lista attività', 90),
    ('Documenti', 'Prenotazione spa', 100),
    ('Elettronica', 'Power bank', 10),
    ('Elettronica', 'Caricabatterie multi', 20),
    ('Elettronica', 'Cavo unico', 30),
    ('Elettronica', 'Adattatore', 40),
    ('Elettronica', 'Auricolari', 50),
    ('Elettronica', 'Supporto telefono', 60),
    ('Elettronica', 'Caricabatterie auto', 70),
    ('Elettronica', 'Hub mini', 80),
    ('Elettronica', 'Batteria slim', 90),
    ('Elettronica', 'Caricabatterie wireless', 100),
    ('Farmaci', 'Antidolorifico', 10),
    ('Farmaci', 'Cerotti', 20),
    ('Farmaci', 'Antiacido', 30),
    ('Farmaci', 'Antistaminico', 40),
    ('Farmaci', 'Disinfettante', 50),
    ('Farmaci', 'Integratore', 60),
    ('Farmaci', 'Collirio', 70),
    ('Farmaci', 'Melatonina', 80),
    ('Farmaci', 'Repellente', 90),
    ('Farmaci', 'Spray nasale', 100),
    ('Accessori', 'Zaino da giorno', 10),
    ('Accessori', 'Borraccia', 20),
    ('Accessori', 'Ombrello', 30),
    ('Accessori', 'Organizer valigia', 40),
    ('Accessori', 'Lucchetto', 50),
    ('Accessori', 'Beauty case', 60),
    ('Accessori', 'Borsa pieghevole', 70),
    ('Accessori', 'Portaoggetti', 80),
    ('Accessori', 'Cintura portasoldi', 90),
    ('Accessori', 'Sacca spesa', 100),
    ('Extra', 'Libro', 10),
    ('Extra', 'Snack premium', 20),
    ('Extra', 'Giochi carte', 30),
    ('Extra', 'Thermos', 40),
    ('Extra', 'Carte', 50),
    ('Extra', 'Rivista', 60),
    ('Extra', 'Diario viaggio', 70),
    ('Extra', 'Playlist offline', 80),
    ('Extra', 'Giochi', 90),
    ('Extra', 'Snack', 100),
    ('Bambini', 'Pigiama preferito', 10),
    ('Bambini', 'Giocattolo unico', 20),
    ('Bambini', 'Cambio completo', 30),
    ('Bambini', 'Merenda', 40),
    ('Bambini', 'Borraccia bimbo', 50),
    ('Bambini', 'Giochi', 60),
    ('Bambini', 'Felpa', 70),
    ('Bambini', 'Scarpe', 80),
    ('Bambini', 'Libro', 90),
    ('Bambini', 'Thermos', 100),
    ('Animali', 'Snack pet extra', 10),
    ('Animali', 'Giochi', 20),
    ('Animali', 'Coperta', 30),
    ('Animali', 'Ciotole', 40),
    ('Animali', 'Guinzaglio', 50),
    ('Animali', 'Tappetino', 60),
    ('Animali', 'Borsa', 70),
    ('Animali', 'Documenti pet', 80),
    ('Animali', 'Cibo', 90),
    ('Animali', 'Salviette', 100)
) AS v(category, name, sort_order)
WHERE s.user_id IS NULL AND s.title ILIKE 'Template Weekend'
ON CONFLICT (template_id, category, name) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();

-- Template: Template Famiglia
DELETE FROM public.packing_template_items
WHERE template_id IN (
  SELECT id FROM public.suitcases WHERE user_id IS NULL AND title ILIKE 'Template Famiglia'
);

INSERT INTO public.packing_template_items (template_id, category, name, sort_order, is_active)
SELECT s.id, v.category, v.name, v.sort_order, true
FROM public.suitcases s
CROSS JOIN (
  VALUES
    ('Abbigliamento', 'Giacca impermeabile', 10),
    ('Abbigliamento', 'Pantalone elastico', 20),
    ('Abbigliamento', 'Scarpe chiuse', 30),
    ('Abbigliamento', 'Maglietta scura', 40),
    ('Abbigliamento', 'Polo', 50),
    ('Abbigliamento', 'Pantaloncini', 60),
    ('Abbigliamento', 'Sneaker', 70),
    ('Abbigliamento', 'Camicia', 80),
    ('Abbigliamento', 'Cappello', 90),
    ('Abbigliamento', 'Felpa', 100),
    ('Igiene', 'Gel mani', 10),
    ('Igiene', 'Deodorante', 20),
    ('Igiene', 'Salviette disinfettanti', 30),
    ('Igiene', 'Crema mani', 40),
    ('Igiene', 'Shampoo travel', 50),
    ('Igiene', 'Dentifricio travel', 60),
    ('Igiene', 'Balsamo labbra', 70),
    ('Igiene', 'Crema solare', 80),
    ('Igiene', 'Spray igienizzante', 90),
    ('Igiene', 'Sapone mani portatile', 100),
    ('Documenti', 'Documenti bambini', 10),
    ('Documenti', 'Libretto sanitario bambino', 20),
    ('Documenti', 'Autorizzazione minori', 30),
    ('Documenti', 'Tessera pediatra', 40),
    ('Documenti', 'Lista farmaci bambino', 50),
    ('Documenti', 'Documenti pet', 60),
    ('Documenti', 'Passaporto pet', 70),
    ('Documenti', 'Certificati vaccini bimbo', 80),
    ('Documenti', 'Assicurazione famiglia', 90),
    ('Documenti', 'Documenti seggiolino', 100),
    ('Elettronica', 'Tablet bambini', 10),
    ('Elettronica', 'Caricabatterie multi', 20),
    ('Elettronica', 'Power bank', 30),
    ('Elettronica', 'Adattatore', 40),
    ('Elettronica', 'Cavo lungo', 50),
    ('Elettronica', 'Supporto tablet', 60),
    ('Elettronica', 'Auricolari bambini', 70),
    ('Elettronica', 'Caricabatterie wireless', 80),
    ('Elettronica', 'Batteria tablet', 90),
    ('Elettronica', 'Adattatore auto', 100),
    ('Farmaci', 'Termometro', 10),
    ('Farmaci', 'Farmaci febbre bambini', 20),
    ('Farmaci', 'Soluzione nasale bambini', 30),
    ('Farmaci', 'Crema barriera', 40),
    ('Farmaci', 'Antistaminico bambini', 50),
    ('Farmaci', 'Farmaci cinetosi bambini', 60),
    ('Farmaci', 'Cerotti bambini', 70),
    ('Farmaci', 'Antipiretico bambini', 80),
    ('Farmaci', 'Integratore bambini', 90),
    ('Farmaci', 'Collirio bambini', 100),
    ('Accessori', 'Borsa pannolini', 10),
    ('Accessori', 'Borsa termica', 20),
    ('Accessori', 'Organizer famiglia', 30),
    ('Accessori', 'Borsa giocattoli', 40),
    ('Accessori', 'Borsa spesa', 50),
    ('Accessori', 'Lucchetto', 60),
    ('Accessori', 'Portadocumenti', 70),
    ('Accessori', 'Occhiali da sole', 80),
    ('Accessori', 'Zaino da giorno', 90),
    ('Accessori', 'Borraccia', 100),
    ('Extra', 'Giochi viaggio', 10),
    ('Extra', 'Carte', 20),
    ('Extra', 'Puzzle tascabile', 30),
    ('Extra', 'Peluche', 40),
    ('Extra', 'Album colori', 50),
    ('Extra', 'Giochi auto', 60),
    ('Extra', 'Snack bambini', 70),
    ('Extra', 'Giocattolo preferito', 80),
    ('Extra', 'Snack pet', 90),
    ('Extra', 'Libro bambini', 100),
    ('Bambini', 'Ciuccio', 10),
    ('Bambini', 'Latte in polvere', 20),
    ('Bambini', 'Bavaglino', 30),
    ('Bambini', 'Passeggino', 40),
    ('Bambini', 'Marsupio', 50),
    ('Bambini', 'Fasciatoio portatile', 60),
    ('Bambini', 'Set pappa', 70),
    ('Bambini', 'Termos pappa', 80),
    ('Bambini', 'Crema barriera', 90),
    ('Bambini', 'Monitor neonato', 100),
    ('Animali', 'Tappetino viaggio pet', 10),
    ('Animali', 'Ciotole pieghevoli', 20),
    ('Animali', 'Pettorina', 30),
    ('Animali', 'Cuccia portatile', 40),
    ('Animali', 'Gioco preferito', 50),
    ('Animali', 'Trasportino', 60),
    ('Animali', 'Museruola', 70),
    ('Animali', 'Spazzola pet', 80),
    ('Animali', 'Borsa cibo', 90),
    ('Animali', 'Salviette pet', 100)
) AS v(category, name, sort_order)
WHERE s.user_id IS NULL AND s.title ILIKE 'Template Famiglia'
ON CONFLICT (template_id, category, name) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();
