-- =============================================================================
-- MIGRATION: 20260730120001_seed_myworld_design_system_rules.sql
-- DESCRIZIONE: Seed sezione Design System MyWorld Style (riferimento Valigia)
-- SICUREZZA:   UPSERT su component_key
-- =============================================================================

INSERT INTO public.design_system_rules (
    section,
    element_name,
    component_key,
    font_family,
    text_size,
    font_weight,
    text_transform,
    tracking,
    color_class,
    line_height,
    effect_class,
    css_class,
    preview_text
)
VALUES
    (
        'myworld',
        'Barra header sezione',
        'myworld_section_header_bar',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'shrink-0 rounded-xl border border-slate-800/80 bg-slate-950/40 px-3 py-2.5 mb-3',
        'Header sezione'
    ),
    (
        'myworld',
        'Titolo sezione',
        'myworld_section_title',
        'font-sans',
        'text-sm',
        'font-bold',
        'normal-case',
        NULL,
        'text-white',
        NULL,
        'none',
        NULL,
        'Valigia'
    ),
    (
        'myworld',
        'Icona titolo sezione',
        'myworld_section_icon',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'w-4 h-4 text-indigo-300 shrink-0',
        'Icona'
    ),
    (
        'myworld',
        'Descrizione sezione',
        'myworld_section_description',
        'font-sans',
        NULL,
        NULL,
        'normal-case',
        NULL,
        NULL,
        NULL,
        'none',
        'text-[11px] text-slate-500 mt-1 leading-snug',
        'Le tue valigie e i template, pronti da aprire quando ti servono.'
    ),
    (
        'myworld',
        'Pannello sezione',
        'myworld_section_panel',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'flex flex-col min-h-0 rounded-xl border border-slate-800 bg-slate-900/50 overflow-hidden',
        'Pannello'
    ),
    (
        'myworld',
        'Header pannello colonna',
        'myworld_panel_header',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'shrink-0 flex items-center justify-between gap-2 px-3 py-2 border-b border-slate-800/80',
        'Header pannello'
    ),
    (
        'myworld',
        'Riga lista',
        'myworld_list_row',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'flex items-stretch gap-1 rounded-xl border border-slate-800 bg-slate-900/60',
        'Riga'
    ),
    (
        'myworld',
        'Titolo riga lista',
        'myworld_list_title',
        'font-sans',
        NULL,
        NULL,
        'normal-case',
        NULL,
        NULL,
        NULL,
        'none',
        'block text-sm font-semibold text-white truncate',
        'Nome elemento'
    ),
    (
        'myworld',
        'Meta riga lista',
        'myworld_list_meta',
        'font-sans',
        NULL,
        NULL,
        'normal-case',
        NULL,
        NULL,
        NULL,
        'none',
        'block text-[10px] text-slate-500 mt-0.5',
        'Apri valigia'
    ),
    (
        'myworld',
        'Pulsante chrome (Nuova / azione)',
        'myworld_chrome_btn',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'inline-flex items-center gap-1 rounded-lg border border-slate-700 bg-slate-900 px-2.5 py-1.5 text-[11px] font-semibold text-slate-200 hover:bg-slate-800 disabled:opacity-50',
        'Nuova'
    )
ON CONFLICT (component_key) DO UPDATE SET
    section = EXCLUDED.section,
    element_name = EXCLUDED.element_name,
    font_family = EXCLUDED.font_family,
    text_size = EXCLUDED.text_size,
    font_weight = EXCLUDED.font_weight,
    text_transform = EXCLUDED.text_transform,
    tracking = EXCLUDED.tracking,
    color_class = EXCLUDED.color_class,
    line_height = EXCLUDED.line_height,
    effect_class = EXCLUDED.effect_class,
    css_class = EXCLUDED.css_class,
    preview_text = EXCLUDED.preview_text;
