-- Macrofase C: allinea packing_standard_items al catalogo congelato

-- Disattiva standard legacy non più nel dominio
UPDATE public.packing_standard_items
SET is_active = false, updated_at = now()
WHERE is_active = true
  AND (category, name) NOT IN (
    ('Abbigliamento', 'Intimo'),
    ('Abbigliamento', 'Calze'),
    ('Abbigliamento', 'T-shirt'),
    ('Abbigliamento', 'Pantaloni'),
    ('Abbigliamento', 'Pigiama'),
    ('Abbigliamento', 'Scarpe da giorno'),
    ('Abbigliamento', 'Canotta'),
    ('Abbigliamento', 'Cintura'),
    ('Abbigliamento', 'Maglietta manica lunga'),
    ('Abbigliamento', 'Giacca leggera'),
    ('Igiene', 'Spazzolino'),
    ('Igiene', 'Dentifricio'),
    ('Igiene', 'Deodorante'),
    ('Igiene', 'Shampoo'),
    ('Igiene', 'Bagnoschiuma'),
    ('Igiene', 'Spazzola capelli'),
    ('Igiene', 'Assorbenti'),
    ('Igiene', 'Crema idratante'),
    ('Igiene', 'Asciugamano'),
    ('Igiene', 'Telo doccia'),
    ('Documenti', 'Documento identità'),
    ('Documenti', 'Tessera sanitaria'),
    ('Documenti', 'Carte di pagamento'),
    ('Documenti', 'Contanti'),
    ('Documenti', 'Prenotazione alloggio'),
    ('Documenti', 'Biglietti trasporto'),
    ('Documenti', 'Copia documenti'),
    ('Documenti', 'Assicurazione viaggio'),
    ('Documenti', 'Patente di guida'),
    ('Documenti', 'Voucher attività'),
    ('Elettronica', 'Smartphone'),
    ('Elettronica', 'Caricabatterie smartphone'),
    ('Elettronica', 'Cavo ricarica'),
    ('Elettronica', 'Cavo di riserva'),
    ('Elettronica', 'Power bank'),
    ('Elettronica', 'Auricolari'),
    ('Elettronica', 'Caricabatterie multiporta'),
    ('Elettronica', 'Adattatore presa universale'),
    ('Elettronica', 'Smartwatch'),
    ('Elettronica', 'Caricabatterie wireless'),
    ('Farmaci', 'Farmaci personali abituali'),
    ('Farmaci', 'Antidolorifico'),
    ('Farmaci', 'Cerotti misti'),
    ('Farmaci', 'Disinfettante'),
    ('Farmaci', 'Antiacido / antidiarroico'),
    ('Accessori', 'Portafoglio'),
    ('Accessori', 'Zaino da giorno'),
    ('Accessori', 'Borraccia'),
    ('Accessori', 'Lucchetto valigia'),
    ('Accessori', 'Orologio'),
    ('Extra', 'Snack'),
    ('Extra', 'Sacchetto spesa pieghevole'),
    ('Extra', 'Libro'),
    ('Extra', 'Giochi carte'),
    ('Extra', 'Thermos'),
    ('Bambini', 'Pannolini'),
    ('Bambini', 'Salviette bimbo'),
    ('Bambini', 'Cambio abbigliamento bambino'),
    ('Bambini', 'Biberon'),
    ('Bambini', 'Snack bambino'),
    ('Animali', 'Cibo pet'),
    ('Animali', 'Ciotole'),
    ('Animali', 'Guinzaglio'),
    ('Animali', 'Sacchetti igienici'),
    ('Animali', 'Libretto sanitario pet')
  );

INSERT INTO public.packing_standard_items (category, name, sort_order, tier, is_active)
VALUES
  ('Abbigliamento', 'Intimo', 10, 'core', true),
  ('Abbigliamento', 'Calze', 20, 'core', true),
  ('Abbigliamento', 'T-shirt', 30, 'core', true),
  ('Abbigliamento', 'Pantaloni', 40, 'core', true),
  ('Abbigliamento', 'Pigiama', 50, 'core', true),
  ('Abbigliamento', 'Scarpe da giorno', 60, 'core', true),
  ('Abbigliamento', 'Canotta', 70, 'core', true),
  ('Abbigliamento', 'Cintura', 80, 'core', true),
  ('Abbigliamento', 'Maglietta manica lunga', 90, 'core', true),
  ('Abbigliamento', 'Giacca leggera', 100, 'core', true),
  ('Igiene', 'Spazzolino', 110, 'core', true),
  ('Igiene', 'Dentifricio', 120, 'core', true),
  ('Igiene', 'Deodorante', 130, 'core', true),
  ('Igiene', 'Shampoo', 140, 'core', true),
  ('Igiene', 'Bagnoschiuma', 150, 'core', true),
  ('Igiene', 'Spazzola capelli', 160, 'core', true),
  ('Igiene', 'Assorbenti', 170, 'core', true),
  ('Igiene', 'Crema idratante', 180, 'core', true),
  ('Igiene', 'Asciugamano', 190, 'core', true),
  ('Igiene', 'Telo doccia', 200, 'core', true),
  ('Documenti', 'Documento identità', 210, 'core', true),
  ('Documenti', 'Tessera sanitaria', 220, 'core', true),
  ('Documenti', 'Carte di pagamento', 230, 'core', true),
  ('Documenti', 'Contanti', 240, 'core', true),
  ('Documenti', 'Prenotazione alloggio', 250, 'core', true),
  ('Documenti', 'Biglietti trasporto', 260, 'core', true),
  ('Documenti', 'Copia documenti', 270, 'core', true),
  ('Documenti', 'Assicurazione viaggio', 280, 'core', true),
  ('Documenti', 'Patente di guida', 290, 'core', true),
  ('Documenti', 'Voucher attività', 300, 'core', true),
  ('Elettronica', 'Smartphone', 310, 'core', true),
  ('Elettronica', 'Caricabatterie smartphone', 320, 'core', true),
  ('Elettronica', 'Cavo ricarica', 330, 'core', true),
  ('Elettronica', 'Cavo di riserva', 340, 'core', true),
  ('Elettronica', 'Power bank', 350, 'core', true),
  ('Elettronica', 'Auricolari', 360, 'core', true),
  ('Elettronica', 'Caricabatterie multiporta', 370, 'core', true),
  ('Elettronica', 'Adattatore presa universale', 380, 'core', true),
  ('Elettronica', 'Smartwatch', 390, 'core', true),
  ('Elettronica', 'Caricabatterie wireless', 400, 'core', true),
  ('Farmaci', 'Farmaci personali abituali', 410, 'core', true),
  ('Farmaci', 'Antidolorifico', 420, 'core', true),
  ('Farmaci', 'Cerotti misti', 430, 'core', true),
  ('Farmaci', 'Disinfettante', 440, 'core', true),
  ('Farmaci', 'Antiacido / antidiarroico', 450, 'core', true),
  ('Accessori', 'Portafoglio', 460, 'core', true),
  ('Accessori', 'Zaino da giorno', 470, 'core', true),
  ('Accessori', 'Borraccia', 480, 'core', true),
  ('Accessori', 'Lucchetto valigia', 490, 'core', true),
  ('Accessori', 'Orologio', 500, 'core', true),
  ('Extra', 'Snack', 510, 'core', true),
  ('Extra', 'Sacchetto spesa pieghevole', 520, 'core', true),
  ('Extra', 'Libro', 530, 'core', true),
  ('Extra', 'Giochi carte', 540, 'core', true),
  ('Extra', 'Thermos', 550, 'core', true),
  ('Bambini', 'Pannolini', 560, 'additional', true),
  ('Bambini', 'Salviette bimbo', 570, 'additional', true),
  ('Bambini', 'Cambio abbigliamento bambino', 580, 'additional', true),
  ('Bambini', 'Biberon', 590, 'additional', true),
  ('Bambini', 'Snack bambino', 600, 'additional', true),
  ('Animali', 'Cibo pet', 610, 'additional', true),
  ('Animali', 'Ciotole', 620, 'additional', true),
  ('Animali', 'Guinzaglio', 630, 'additional', true),
  ('Animali', 'Sacchetti igienici', 640, 'additional', true),
  ('Animali', 'Libretto sanitario pet', 650, 'additional', true)
ON CONFLICT (category, name) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  tier = EXCLUDED.tier,
  is_active = true,
  updated_at = now();
