-- Macrofase C: allinea packing_ai_catalog al catalogo congelato

UPDATE public.packing_ai_catalog
SET is_active = false, updated_at = now()
WHERE is_active = true
  AND name NOT IN (
    'Piumino packable',
    'Giacca pesante',
    'K-way',
    'Guanti pesanti',
    'Sciarpa lana',
    'Abbigliamento termico',
    'Pantaloni impermeabili',
    'Stivali pioggia',
    'Vestito cerimonia',
    'Cuffia nuoto',
    'Muta leggera',
    'Camice antimoscerini',
    'Sandali trekking',
    'Pantalone convertibile',
    'Abito cocktail',
    'Slip mare',
    'Reggiseno sportivo',
    'Softshell',
    'Poncho',
    'Bandana',
    'Leggings',
    'Overshirt',
    'Fascia capelli',
    'Ciabatte hotel',
    'Maglione pesante',
    'Rasoi',
    'Fazzoletti',
    'Flaconi silicone',
    'Cotton fioc',
    'Detergente intimo',
    'Profumo solido',
    'Shampoo secco',
    'Maschera capelli',
    'Filo interdentale',
    'Collutorio travel',
    'Crema solare viso',
    'Spazzolino elettrico',
    'Rasoi usa e getta',
    'Kit barba',
    'Crema antisfregamento',
    'Talco',
    'Crema piedi',
    'Smaltoremover',
    'Salviette struccanti',
    'Deodorante crystal',
    'Spugna viaggio',
    'Bagnoschiuma solido',
    'Gel doccia solido',
    'Patch acne',
    'Pettine tascabile',
    'Passaporto',
    'Visto',
    'Patente internazionale',
    'Green card',
    'Certificato vaccinazioni',
    'Carta imbarco',
    'Boarding pass backup',
    'Traduzione documenti',
    'Procura',
    'Voucher noleggio auto',
    'Abbonamento metro',
    'QR musei backup',
    'Certificato medico sport',
    'Lista farmaci tradotta',
    'Tessere fidelity',
    'Permesso soggiorno',
    'ESTA',
    'Assicurazione estesa',
    'Copia passaporto',
    'Licenza pesca internazionale',
    'Documenti auto noleggio',
    'Carta imbarco pet',
    'Tessera europea assicurazione',
    'Permesso caccia',
    'Documenti matrimonio',
    'AirTag',
    'Adattatore UK',
    'Adattatore US',
    'Multipresa compatta',
    'SD card',
    'Obiettivo clip',
    'Drone mini',
    'Convertitore voltaggio',
    'Caricabatterie fotocamera',
    'Batterie AA ricaricabili',
    'Splitter audio',
    'Tastiera pieghevole',
    'Stylus',
    'Walkie talkie',
    'Lampada USB',
    'Filtro privacy webcam',
    'Proiettore pocket',
    'Caricabatterie orologio',
    'Banda fitness',
    'Tracker bagaglio',
    'Caricabatterie rapido',
    'Cuffie over-ear',
    'Microfono lavalier',
    'Scheda SIM backup',
    'Power bank slim',
    'Fermenti lattici',
    'Garze sterili',
    'Bendaggio elastico',
    'Pinzette',
    'Forbici mediche',
    'Probiotici',
    'Pomata herpes',
    'Spray gola',
    'Vitamina C',
    'Antimalarico',
    'Cerotti vesciche grandi',
    'Gel scottature',
    'Antipiretico',
    'Crema emorroidi',
    'Antiviral',
    'Pomata punture',
    'Sali reidratanti',
    'Antibiotico topico',
    'Ghiaccio spray',
    'Repellente forte',
    'Integratori minerali',
    'Antistaminico sedativo',
    'Crema scottature II grado',
    'Garze',
    'Kit pronto soccorso leggero',
    'Packing cubes',
    'Lucchetto TSA',
    'Etichette bagaglio',
    'Bilancia bagaglio',
    'Cintura portasoldi',
    'Lucchetto cavo',
    'Copri valigia',
    'Organizer scarpe',
    'Sacchetti compressione',
    'Gancio borsa',
    'Custodia occhiali sole',
    'Porta passaporto RFID',
    'Cuscino viaggio',
    'Mascherina occhi',
    'Tappi orecchie',
    'Adattatore sedile aereo',
    'Ganci appendini',
    'Elastici vestiti',
    'Borsa frigo',
    'Moschettone',
    'Clip multiuso',
    'Occhiali da vista',
    'Portabottiglia',
    'Sacca spesa',
    'Borsa a tracolla',
    'Ventaglio',
    'Kit lavaggio panni',
    'Sacchetto panni sporchi',
    'Corda stendino',
    'Mollette',
    'Speaker bluetooth',
    'Polaroid',
    'Coperta viaggio',
    'Cuscino gonfiabile',
    'Sedia pieghevole',
    'Ombrello grande',
    'Kit cucina leggero',
    'Posate travel',
    'Sacco liner',
    'Zaino idratazione',
    'Giornale viaggio',
    'Binocolo compatto',
    'Drone',
    'Carte speciali',
    'Hamaca',
    'Thermos grande',
    'Candele travel',
    'Giochi da tavolo',
    'Pallone',
    'Set picnic',
    'Seggiolino auto',
    'Rialzo seggiolino',
    'Adattatore passeggino aereo',
    'Sterilizzatore biberon',
    'Scaldabiberon',
    'Sacchetti pannolini',
    'Album adesivi',
    'Libri illustrati',
    'Zainetto autonomia',
    'Tutina extra',
    'Scarpine',
    'Porta pappa',
    'Tappetino cambio',
    'Baby monitor',
    'Zaino reins',
    'Bavaglino silicone',
    'Grembiule',
    'Giochi bagno',
    'Pennarelli lavabili',
    'Pannolini notte',
    'Ciuccio ricambio',
    'Coperta sicurezza',
    'Nanna portatile',
    'Peluche ricambio',
    'Seggiolino bici',
    'Spazzola',
    'Shampoo pet',
    'Tagliaunghie',
    'Farmaci pet abituali',
    'Sedativo viaggio',
    'Carrier aereo omologato',
    'Tappetino assorbente',
    'Cintura auto',
    'Barriera auto',
    'Collare LED',
    'Cooling mat',
    'Bottiglia portatile',
    'Snack dental',
    'Felpa pet',
    'GPS pet',
    'Imbracatura trekking',
    'Documenti pet UE',
    'Gioco puzzle',
    'Coperta riscaldante',
    'Kit pronto soccorso',
    'Guinzaglio retrattile',
    'Ciotola antivoracità',
    'Pettorina riflettente',
    'Borsa trasporto',
    'Microchip'
  );

INSERT INTO public.packing_ai_catalog (name, category, tags, sort_order, is_active)
VALUES
  ('Piumino packable', 'Abbigliamento', ARRAY['montagna', 'freddo', 'weekend'], 10, true),
  ('Giacca pesante', 'Abbigliamento', ARRAY['montagna', 'freddo'], 20, true),
  ('K-way', 'Abbigliamento', ARRAY['pioggia', 'montagna'], 30, true),
  ('Guanti pesanti', 'Abbigliamento', ARRAY['freddo', 'montagna'], 40, true),
  ('Sciarpa lana', 'Abbigliamento', ARRAY['freddo', 'cultura'], 50, true),
  ('Abbigliamento termico', 'Abbigliamento', ARRAY['freddo', 'montagna'], 60, true),
  ('Pantaloni impermeabili', 'Abbigliamento', ARRAY['pioggia', 'montagna'], 70, true),
  ('Stivali pioggia', 'Abbigliamento', ARRAY['pioggia'], 80, true),
  ('Vestito cerimonia', 'Abbigliamento', ARRAY['business', 'cultura'], 90, true),
  ('Cuffia nuoto', 'Abbigliamento', ARRAY['mare', 'lago'], 100, true),
  ('Muta leggera', 'Abbigliamento', ARRAY['mare'], 110, true),
  ('Camice antimoscerini', 'Abbigliamento', ARRAY['montagna', 'lago'], 120, true),
  ('Sandali trekking', 'Abbigliamento', ARRAY['montagna'], 130, true),
  ('Pantalone convertibile', 'Abbigliamento', ARRAY['montagna', 'lago'], 140, true),
  ('Abito cocktail', 'Abbigliamento', ARRAY['business', 'weekend'], 150, true),
  ('Slip mare', 'Abbigliamento', ARRAY['mare', 'lago'], 160, true),
  ('Reggiseno sportivo', 'Abbigliamento', ARRAY['mare', 'montagna'], 170, true),
  ('Softshell', 'Abbigliamento', ARRAY['montagna'], 180, true),
  ('Poncho', 'Abbigliamento', ARRAY['pioggia'], 190, true),
  ('Bandana', 'Abbigliamento', ARRAY['mare', 'montagna', 'caldo'], 200, true),
  ('Leggings', 'Abbigliamento', ARRAY['weekend', 'cultura'], 210, true),
  ('Overshirt', 'Abbigliamento', ARRAY['cultura', 'weekend'], 220, true),
  ('Fascia capelli', 'Abbigliamento', ARRAY['mare', 'sport'], 230, true),
  ('Ciabatte hotel', 'Abbigliamento', ARRAY['business', 'lungo_raggio'], 240, true),
  ('Maglione pesante', 'Abbigliamento', ARRAY['freddo', 'weekend'], 250, true),
  ('Rasoi', 'Igiene', ARRAY['universal'], 260, true),
  ('Fazzoletti', 'Igiene', ARRAY['universal'], 270, true),
  ('Flaconi silicone', 'Igiene', ARRAY['lungo_raggio', 'volo'], 280, true),
  ('Cotton fioc', 'Igiene', ARRAY['universal'], 290, true),
  ('Detergente intimo', 'Igiene', ARRAY['universal'], 300, true),
  ('Profumo solido', 'Igiene', ARRAY['business', 'weekend'], 310, true),
  ('Shampoo secco', 'Igiene', ARRAY['weekend', 'business'], 320, true),
  ('Maschera capelli', 'Igiene', ARRAY['mare', 'lungo_raggio'], 330, true),
  ('Filo interdentale', 'Igiene', ARRAY['universal'], 340, true),
  ('Collutorio travel', 'Igiene', ARRAY['lungo_raggio'], 350, true),
  ('Crema solare viso', 'Igiene', ARRAY['mare', 'montagna'], 360, true),
  ('Spazzolino elettrico', 'Igiene', ARRAY['business', 'lungo_raggio'], 370, true),
  ('Rasoi usa e getta', 'Igiene', ARRAY['weekend'], 380, true),
  ('Kit barba', 'Igiene', ARRAY['business'], 390, true),
  ('Crema antisfregamento', 'Igiene', ARRAY['montagna', 'cultura'], 400, true),
  ('Talco', 'Igiene', ARRAY['caldo', 'mare'], 410, true),
  ('Crema piedi', 'Igiene', ARRAY['cultura', 'montagna'], 420, true),
  ('Smaltoremover', 'Igiene', ARRAY['weekend', 'lungo_raggio'], 430, true),
  ('Salviette struccanti', 'Igiene', ARRAY['business', 'weekend'], 440, true),
  ('Deodorante crystal', 'Igiene', ARRAY['universal'], 450, true),
  ('Spugna viaggio', 'Igiene', ARRAY['mare', 'lago'], 460, true),
  ('Bagnoschiuma solido', 'Igiene', ARRAY['lungo_raggio'], 470, true),
  ('Gel doccia solido', 'Igiene', ARRAY['lungo_raggio'], 480, true),
  ('Patch acne', 'Igiene', ARRAY['weekend'], 490, true),
  ('Pettine tascabile', 'Igiene', ARRAY['business', 'weekend'], 500, true),
  ('Passaporto', 'Documenti', ARRAY['volo', 'lungo_raggio'], 510, true),
  ('Visto', 'Documenti', ARRAY['volo', 'lungo_raggio'], 520, true),
  ('Patente internazionale', 'Documenti', ARRAY['lungo_raggio'], 530, true),
  ('Green card', 'Documenti', ARRAY['lungo_raggio'], 540, true),
  ('Certificato vaccinazioni', 'Documenti', ARRAY['volo', 'lungo_raggio'], 550, true),
  ('Carta imbarco', 'Documenti', ARRAY['volo'], 560, true),
  ('Boarding pass backup', 'Documenti', ARRAY['volo'], 570, true),
  ('Traduzione documenti', 'Documenti', ARRAY['lungo_raggio', 'business'], 580, true),
  ('Procura', 'Documenti', ARRAY['lungo_raggio'], 590, true),
  ('Voucher noleggio auto', 'Documenti', ARRAY['weekend', 'lungo_raggio'], 600, true),
  ('Abbonamento metro', 'Documenti', ARRAY['cultura', 'business'], 610, true),
  ('QR musei backup', 'Documenti', ARRAY['cultura'], 620, true),
  ('Certificato medico sport', 'Documenti', ARRAY['montagna', 'mare'], 630, true),
  ('Lista farmaci tradotta', 'Documenti', ARRAY['lungo_raggio'], 640, true),
  ('Tessere fidelity', 'Documenti', ARRAY['business', 'weekend'], 650, true),
  ('Permesso soggiorno', 'Documenti', ARRAY['lungo_raggio'], 660, true),
  ('ESTA', 'Documenti', ARRAY['volo'], 670, true),
  ('Assicurazione estesa', 'Documenti', ARRAY['lungo_raggio', 'montagna'], 680, true),
  ('Copia passaporto', 'Documenti', ARRAY['volo', 'lungo_raggio'], 690, true),
  ('Licenza pesca internazionale', 'Documenti', ARRAY['lago'], 700, true),
  ('Documenti auto noleggio', 'Documenti', ARRAY['weekend', 'lungo_raggio'], 710, true),
  ('Carta imbarco pet', 'Documenti', ARRAY['volo', 'pet'], 720, true),
  ('Tessera europea assicurazione', 'Documenti', ARRAY['lungo_raggio'], 730, true),
  ('Permesso caccia', 'Documenti', ARRAY['montagna', 'lago'], 740, true),
  ('Documenti matrimonio', 'Documenti', ARRAY['cultura', 'weekend'], 750, true),
  ('AirTag', 'Elettronica', ARRAY['volo', 'lungo_raggio'], 760, true),
  ('Adattatore UK', 'Elettronica', ARRAY['lungo_raggio', 'volo'], 770, true),
  ('Adattatore US', 'Elettronica', ARRAY['lungo_raggio', 'volo'], 780, true),
  ('Multipresa compatta', 'Elettronica', ARRAY['lungo_raggio', 'business'], 790, true),
  ('SD card', 'Elettronica', ARRAY['cultura', 'mare'], 800, true),
  ('Obiettivo clip', 'Elettronica', ARRAY['mare', 'cultura'], 810, true),
  ('Drone mini', 'Elettronica', ARRAY['mare', 'montagna'], 820, true),
  ('Convertitore voltaggio', 'Elettronica', ARRAY['lungo_raggio', 'volo'], 830, true),
  ('Caricabatterie fotocamera', 'Elettronica', ARRAY['cultura', 'mare'], 840, true),
  ('Batterie AA ricaricabili', 'Elettronica', ARRAY['montagna', 'lungo_raggio'], 850, true),
  ('Splitter audio', 'Elettronica', ARRAY['treno', 'volo'], 860, true),
  ('Tastiera pieghevole', 'Elettronica', ARRAY['business'], 870, true),
  ('Stylus', 'Elettronica', ARRAY['business'], 880, true),
  ('Walkie talkie', 'Elettronica', ARRAY['montagna', 'famiglia'], 890, true),
  ('Lampada USB', 'Elettronica', ARRAY['lungo_raggio'], 900, true),
  ('Filtro privacy webcam', 'Elettronica', ARRAY['business'], 910, true),
  ('Proiettore pocket', 'Elettronica', ARRAY['famiglia', 'weekend'], 920, true),
  ('Caricabatterie orologio', 'Elettronica', ARRAY['universal'], 930, true),
  ('Banda fitness', 'Elettronica', ARRAY['montagna', 'mare'], 940, true),
  ('Tracker bagaglio', 'Elettronica', ARRAY['volo', 'lungo_raggio'], 950, true),
  ('Caricabatterie rapido', 'Elettronica', ARRAY['universal'], 960, true),
  ('Cuffie over-ear', 'Elettronica', ARRAY['treno', 'volo'], 970, true),
  ('Microfono lavalier', 'Elettronica', ARRAY['business'], 980, true),
  ('Scheda SIM backup', 'Elettronica', ARRAY['lungo_raggio', 'volo'], 990, true),
  ('Power bank slim', 'Elettronica', ARRAY['weekend', 'business'], 1000, true),
  ('Fermenti lattici', 'Farmaci', ARRAY['farmacia', 'lungo_raggio'], 1010, true),
  ('Garze sterili', 'Farmaci', ARRAY['farmacia', 'montagna'], 1020, true),
  ('Bendaggio elastico', 'Farmaci', ARRAY['farmacia', 'montagna'], 1030, true),
  ('Pinzette', 'Farmaci', ARRAY['farmacia'], 1040, true),
  ('Forbici mediche', 'Farmaci', ARRAY['farmacia'], 1050, true),
  ('Probiotici', 'Farmaci', ARRAY['farmacia', 'lungo_raggio'], 1060, true),
  ('Pomata herpes', 'Farmaci', ARRAY['farmacia'], 1070, true),
  ('Spray gola', 'Farmaci', ARRAY['farmacia', 'freddo'], 1080, true),
  ('Vitamina C', 'Farmaci', ARRAY['farmacia', 'freddo'], 1090, true),
  ('Antimalarico', 'Farmaci', ARRAY['lungo_raggio'], 1100, true),
  ('Cerotti vesciche grandi', 'Farmaci', ARRAY['montagna', 'cultura'], 1110, true),
  ('Gel scottature', 'Farmaci', ARRAY['mare', 'caldo'], 1120, true),
  ('Antipiretico', 'Farmaci', ARRAY['farmacia', 'famiglia'], 1130, true),
  ('Crema emorroidi', 'Farmaci', ARRAY['farmacia'], 1140, true),
  ('Antiviral', 'Farmaci', ARRAY['farmacia'], 1150, true),
  ('Pomata punture', 'Farmaci', ARRAY['mare', 'lago'], 1160, true),
  ('Sali reidratanti', 'Farmaci', ARRAY['mare', 'caldo', 'montagna'], 1170, true),
  ('Antibiotico topico', 'Farmaci', ARRAY['farmacia'], 1180, true),
  ('Ghiaccio spray', 'Farmaci', ARRAY['montagna', 'sport'], 1190, true),
  ('Repellente forte', 'Farmaci', ARRAY['montagna', 'lago'], 1200, true),
  ('Integratori minerali', 'Farmaci', ARRAY['montagna', 'lungo_raggio'], 1210, true),
  ('Antistaminico sedativo', 'Farmaci', ARRAY['volo', 'farmacia'], 1220, true),
  ('Crema scottature II grado', 'Farmaci', ARRAY['mare'], 1230, true),
  ('Garze', 'Farmaci', ARRAY['farmacia'], 1240, true),
  ('Kit pronto soccorso leggero', 'Farmaci', ARRAY['montagna', 'famiglia'], 1250, true),
  ('Packing cubes', 'Accessori', ARRAY['lungo_raggio'], 1260, true),
  ('Lucchetto TSA', 'Accessori', ARRAY['volo', 'lungo_raggio'], 1270, true),
  ('Etichette bagaglio', 'Accessori', ARRAY['volo', 'lungo_raggio'], 1280, true),
  ('Bilancia bagaglio', 'Accessori', ARRAY['volo'], 1290, true),
  ('Cintura portasoldi', 'Accessori', ARRAY['cultura', 'lungo_raggio'], 1300, true),
  ('Lucchetto cavo', 'Accessori', ARRAY['lungo_raggio'], 1310, true),
  ('Copri valigia', 'Accessori', ARRAY['volo', 'lungo_raggio'], 1320, true),
  ('Organizer scarpe', 'Accessori', ARRAY['lungo_raggio', 'business'], 1330, true),
  ('Sacchetti compressione', 'Accessori', ARRAY['lungo_raggio', 'montagna'], 1340, true),
  ('Gancio borsa', 'Accessori', ARRAY['business', 'weekend'], 1350, true),
  ('Custodia occhiali sole', 'Accessori', ARRAY['mare', 'montagna'], 1360, true),
  ('Porta passaporto RFID', 'Accessori', ARRAY['volo', 'lungo_raggio'], 1370, true),
  ('Cuscino viaggio', 'Accessori', ARRAY['volo', 'treno'], 1380, true),
  ('Mascherina occhi', 'Accessori', ARRAY['volo', 'treno'], 1390, true),
  ('Tappi orecchie', 'Accessori', ARRAY['volo', 'treno', 'mare'], 1400, true),
  ('Adattatore sedile aereo', 'Accessori', ARRAY['volo'], 1410, true),
  ('Ganci appendini', 'Accessori', ARRAY['business', 'lungo_raggio'], 1420, true),
  ('Elastici vestiti', 'Accessori', ARRAY['lungo_raggio'], 1430, true),
  ('Borsa frigo', 'Accessori', ARRAY['mare', 'lago', 'famiglia'], 1440, true),
  ('Moschettone', 'Accessori', ARRAY['montagna'], 1450, true),
  ('Clip multiuso', 'Accessori', ARRAY['montagna', 'weekend'], 1460, true),
  ('Occhiali da vista', 'Accessori', ARRAY['universal'], 1470, true),
  ('Portabottiglia', 'Accessori', ARRAY['montagna', 'mare'], 1480, true),
  ('Sacca spesa', 'Accessori', ARRAY['cultura', 'weekend'], 1490, true),
  ('Borsa a tracolla', 'Accessori', ARRAY['cultura', 'weekend'], 1500, true),
  ('Ventaglio', 'Extra', ARRAY['caldo', 'cultura'], 1510, true),
  ('Kit lavaggio panni', 'Extra', ARRAY['lungo_raggio'], 1520, true),
  ('Sacchetto panni sporchi', 'Extra', ARRAY['lungo_raggio'], 1530, true),
  ('Corda stendino', 'Extra', ARRAY['lungo_raggio'], 1540, true),
  ('Mollette', 'Extra', ARRAY['lungo_raggio'], 1550, true),
  ('Speaker bluetooth', 'Extra', ARRAY['mare', 'weekend'], 1560, true),
  ('Polaroid', 'Extra', ARRAY['weekend', 'cultura'], 1570, true),
  ('Coperta viaggio', 'Extra', ARRAY['treno', 'volo'], 1580, true),
  ('Cuscino gonfiabile', 'Extra', ARRAY['volo', 'treno'], 1590, true),
  ('Sedia pieghevole', 'Extra', ARRAY['mare', 'lago'], 1600, true),
  ('Ombrello grande', 'Extra', ARRAY['pioggia', 'cultura'], 1610, true),
  ('Kit cucina leggero', 'Extra', ARRAY['montagna', 'lago'], 1620, true),
  ('Posate travel', 'Extra', ARRAY['lungo_raggio'], 1630, true),
  ('Sacco liner', 'Extra', ARRAY['montagna'], 1640, true),
  ('Zaino idratazione', 'Extra', ARRAY['montagna'], 1650, true),
  ('Giornale viaggio', 'Extra', ARRAY['weekend', 'cultura'], 1660, true),
  ('Binocolo compatto', 'Extra', ARRAY['montagna', 'lago'], 1670, true),
  ('Drone', 'Extra', ARRAY['mare', 'montagna'], 1680, true),
  ('Carte speciali', 'Extra', ARRAY['weekend', 'famiglia'], 1690, true),
  ('Hamaca', 'Extra', ARRAY['mare', 'lago'], 1700, true),
  ('Thermos grande', 'Extra', ARRAY['montagna', 'lungo_raggio'], 1710, true),
  ('Candele travel', 'Extra', ARRAY['weekend'], 1720, true),
  ('Giochi da tavolo', 'Extra', ARRAY['famiglia', 'weekend'], 1730, true),
  ('Pallone', 'Extra', ARRAY['mare', 'famiglia'], 1740, true),
  ('Set picnic', 'Extra', ARRAY['lago', 'weekend'], 1750, true),
  ('Seggiolino auto', 'Bambini', ARRAY['famiglia'], 1760, true),
  ('Rialzo seggiolino', 'Bambini', ARRAY['famiglia'], 1770, true),
  ('Adattatore passeggino aereo', 'Bambini', ARRAY['famiglia', 'volo'], 1780, true),
  ('Sterilizzatore biberon', 'Bambini', ARRAY['famiglia'], 1790, true),
  ('Scaldabiberon', 'Bambini', ARRAY['famiglia'], 1800, true),
  ('Sacchetti pannolini', 'Bambini', ARRAY['famiglia'], 1810, true),
  ('Album adesivi', 'Bambini', ARRAY['famiglia', 'weekend'], 1820, true),
  ('Libri illustrati', 'Bambini', ARRAY['famiglia', 'cultura'], 1830, true),
  ('Zainetto autonomia', 'Bambini', ARRAY['famiglia', 'cultura'], 1840, true),
  ('Tutina extra', 'Bambini', ARRAY['famiglia'], 1850, true),
  ('Scarpine', 'Bambini', ARRAY['famiglia'], 1860, true),
  ('Porta pappa', 'Bambini', ARRAY['famiglia'], 1870, true),
  ('Tappetino cambio', 'Bambini', ARRAY['famiglia'], 1880, true),
  ('Baby monitor', 'Bambini', ARRAY['famiglia'], 1890, true),
  ('Zaino reins', 'Bambini', ARRAY['famiglia', 'cultura'], 1900, true),
  ('Bavaglino silicone', 'Bambini', ARRAY['famiglia'], 1910, true),
  ('Grembiule', 'Bambini', ARRAY['famiglia'], 1920, true),
  ('Giochi bagno', 'Bambini', ARRAY['famiglia', 'mare'], 1930, true),
  ('Pennarelli lavabili', 'Bambini', ARRAY['famiglia', 'weekend'], 1940, true),
  ('Pannolini notte', 'Bambini', ARRAY['famiglia'], 1950, true),
  ('Ciuccio ricambio', 'Bambini', ARRAY['famiglia'], 1960, true),
  ('Coperta sicurezza', 'Bambini', ARRAY['famiglia'], 1970, true),
  ('Nanna portatile', 'Bambini', ARRAY['famiglia'], 1980, true),
  ('Peluche ricambio', 'Bambini', ARRAY['famiglia', 'weekend'], 1990, true),
  ('Seggiolino bici', 'Bambini', ARRAY['famiglia', 'weekend'], 2000, true),
  ('Spazzola', 'Animali', ARRAY['pet'], 2010, true),
  ('Shampoo pet', 'Animali', ARRAY['pet'], 2020, true),
  ('Tagliaunghie', 'Animali', ARRAY['pet'], 2030, true),
  ('Farmaci pet abituali', 'Animali', ARRAY['pet'], 2040, true),
  ('Sedativo viaggio', 'Animali', ARRAY['pet', 'volo'], 2050, true),
  ('Carrier aereo omologato', 'Animali', ARRAY['pet', 'volo'], 2060, true),
  ('Tappetino assorbente', 'Animali', ARRAY['pet'], 2070, true),
  ('Cintura auto', 'Animali', ARRAY['pet', 'famiglia'], 2080, true),
  ('Barriera auto', 'Animali', ARRAY['pet', 'famiglia'], 2090, true),
  ('Collare LED', 'Animali', ARRAY['pet', 'montagna'], 2100, true),
  ('Cooling mat', 'Animali', ARRAY['pet', 'caldo'], 2110, true),
  ('Bottiglia portatile', 'Animali', ARRAY['pet', 'mare'], 2120, true),
  ('Snack dental', 'Animali', ARRAY['pet'], 2130, true),
  ('Felpa pet', 'Animali', ARRAY['pet', 'freddo'], 2140, true),
  ('GPS pet', 'Animali', ARRAY['pet'], 2150, true),
  ('Imbracatura trekking', 'Animali', ARRAY['pet', 'montagna'], 2160, true),
  ('Documenti pet UE', 'Animali', ARRAY['pet', 'lungo_raggio'], 2170, true),
  ('Gioco puzzle', 'Animali', ARRAY['pet'], 2180, true),
  ('Coperta riscaldante', 'Animali', ARRAY['pet', 'freddo'], 2190, true),
  ('Kit pronto soccorso', 'Animali', ARRAY['pet'], 2200, true),
  ('Guinzaglio retrattile', 'Animali', ARRAY['pet', 'cultura'], 2210, true),
  ('Ciotola antivoracità', 'Animali', ARRAY['pet'], 2220, true),
  ('Pettorina riflettente', 'Animali', ARRAY['pet', 'montagna'], 2230, true),
  ('Borsa trasporto', 'Animali', ARRAY['pet', 'volo'], 2240, true),
  ('Microchip', 'Animali', ARRAY['pet', 'lungo_raggio'], 2250, true)
ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();
