-- Seed MACROFASE A: standard items, AI catalog, migrazione template TD

INSERT INTO public.packing_standard_items (category, name, sort_order, tier) VALUES
  ('Documenti', 'Documento identità', 10, 'core'),
  ('Documenti', 'Carte di credito', 20, 'core'),
  ('Documenti', 'Contanti', 30, 'core'),
  ('Documenti', 'Assicurazione viaggio', 40, 'core'),
  ('Elettronica', 'Caricabatterie universale', 50, 'core'),
  ('Farmaci', 'Farmaci base', 60, 'core'),
  ('Extra', 'Borraccia', 70, 'core'),
  ('Extra', 'Zaino da giorno', 80, 'core'),
  ('Accessori', 'Lucchetto valigia', 90, 'core'),
  ('Igiene', 'Spazzolino', 100, 'core'),
  ('Igiene', 'Dentifricio', 110, 'core'),
  ('Igiene', 'Deodorante', 120, 'core'),
  ('Abbigliamento', 'Intimo', 200, 'core'),
  ('Abbigliamento', 'Calze', 210, 'core'),
  ('Abbigliamento', 'T-shirt', 220, 'core'),
  ('Bambini', 'Pannolini', 300, 'additional'),
  ('Animali', 'Cibo pet', 400, 'additional')
ON CONFLICT (category, name) DO NOTHING;

INSERT INTO public.packing_ai_catalog (name, category, tags, sort_order) VALUES
  ('Costume da bagno', 'Abbigliamento', ARRAY['mare'], 10),
  ('Infradito', 'Abbigliamento', ARRAY['mare'], 20),
  ('Sandali', 'Abbigliamento', ARRAY['mare'], 30),
  ('Telo mare', 'Extra', ARRAY['mare'], 40),
  ('Crema solare', 'Igiene', ARRAY['mare'], 50),
  ('Doposole', 'Igiene', ARRAY['mare'], 60),
  ('Occhiali da sole', 'Abbigliamento', ARRAY['mare'], 70),
  ('Borsa mare', 'Extra', ARRAY['mare'], 80),
  ('Cappello da sole', 'Abbigliamento', ARRAY['mare'], 90),
  ('Maschera e boccaglio', 'Extra', ARRAY['mare'], 100),
  ('Custodia impermeabile smartphone', 'Accessori', ARRAY['mare'], 110),
  ('Scarponi trekking', 'Abbigliamento', ARRAY['montagna'], 120),
  ('Giacca a vento', 'Abbigliamento', ARRAY['montagna'], 130),
  ('Zaino trekking', 'Extra', ARRAY['montagna'], 140),
  ('Bastoncini trekking', 'Extra', ARRAY['montagna'], 150),
  ('Calze tecniche', 'Abbigliamento', ARRAY['montagna'], 160),
  ('Borraccia termica', 'Accessori', ARRAY['montagna'], 170),
  ('Torcia LED', 'Extra', ARRAY['montagna'], 180),
  ('Coltellino multiuso', 'Extra', ARRAY['montagna'], 190),
  ('Crema protezione alta', 'Igiene', ARRAY['montagna'], 200),
  ('Gaiters', 'Abbigliamento', ARRAY['montagna'], 210),
  ('Laptop', 'Elettronica', ARRAY['business'], 220),
  ('Camicia', 'Abbigliamento', ARRAY['business'], 230),
  ('Scarpe eleganti', 'Abbigliamento', ARRAY['business'], 240),
  ('Biglietti da visita', 'Documenti', ARRAY['business'], 250),
  ('Organizer cavi', 'Accessori', ARRAY['business'], 260),
  ('Blazer', 'Abbigliamento', ARRAY['business'], 270),
  ('Cravatta', 'Abbigliamento', ARRAY['business'], 280),
  ('Cartelletta documenti', 'Documenti', ARRAY['business'], 290),
  ('Mouse wireless', 'Elettronica', ARRAY['business'], 300),
  ('Adattatore HDMI', 'Elettronica', ARRAY['business'], 310),
  ('Scarpe comode', 'Abbigliamento', ARRAY['cultura'], 320),
  ('Guida turistica', 'Documenti', ARRAY['cultura'], 330),
  ('Zaino leggero', 'Extra', ARRAY['cultura'], 340),
  ('Taccuino e penna', 'Extra', ARRAY['cultura'], 350),
  ('Mappa offline', 'Documenti', ARRAY['cultura'], 360),
  ('Auricolari', 'Elettronica', ARRAY['cultura'], 370),
  ('Power bank', 'Elettronica', ARRAY['cultura'], 380),
  ('Passaporto', 'Documenti', ARRAY['volo'], 390),
  ('Cuscino cervicale', 'Accessori', ARRAY['volo'], 400),
  ('Mascherina occhi 3D', 'Accessori', ARRAY['volo'], 410),
  ('Tappi orecchie', 'Accessori', ARRAY['volo'], 420),
  ('Bilancia bagaglio', 'Accessori', ARRAY['volo'], 430),
  ('Lucchetto TSA', 'Accessori', ARRAY['volo'], 440),
  ('Etichette bagaglio', 'Accessori', ARRAY['volo'], 450),
  ('Porta passaporto RFID', 'Accessori', ARRAY['volo'], 460),
  ('Calze a compressione', 'Abbigliamento', ARRAY['volo'], 470),
  ('Adattatore cuffie aereo', 'Elettronica', ARRAY['volo'], 480),
  ('Biglietto treno', 'Documenti', ARRAY['treno'], 490),
  ('Cuffie noise-cancelling', 'Elettronica', ARRAY['treno'], 500),
  ('Libro', 'Extra', ARRAY['treno'], 510),
  ('Snack', 'Extra', ARRAY['treno'], 520),
  ('Cuscino da viaggio', 'Accessori', ARRAY['treno'], 530),
  ('Piumino pesante', 'Abbigliamento', ARRAY['freddo'], 540),
  ('Guanti', 'Abbigliamento', ARRAY['freddo'], 550),
  ('Sciarpa', 'Abbigliamento', ARRAY['freddo'], 560),
  ('Berretto lana', 'Abbigliamento', ARRAY['freddo'], 570),
  ('Abbigliamento termico', 'Abbigliamento', ARRAY['freddo'], 580),
  ('Calze lana', 'Abbigliamento', ARRAY['freddo'], 590),
  ('Maglione', 'Abbigliamento', ARRAY['freddo'], 600),
  ('Burrocacao protettivo', 'Igiene', ARRAY['freddo'], 610),
  ('Cappello sole', 'Abbigliamento', ARRAY['caldo'], 620),
  ('Ventaglio', 'Extra', ARRAY['caldo'], 630),
  ('T-shirt leggere', 'Abbigliamento', ARRAY['caldo'], 640),
  ('Pantaloncini', 'Abbigliamento', ARRAY['caldo'], 650),
  ('Sandali aperti', 'Abbigliamento', ARRAY['caldo'], 660),
  ('Borraccia ghiacciata', 'Accessori', ARRAY['caldo'], 670),
  ('Ombrello pieghevole', 'Extra', ARRAY['pioggia'], 680),
  ('Giacca impermeabile', 'Abbigliamento', ARRAY['pioggia'], 690),
  ('Coprizaino antipioggia', 'Extra', ARRAY['pioggia'], 700),
  ('Scarpe waterproof', 'Abbigliamento', ARRAY['pioggia'], 710),
  ('K-way', 'Abbigliamento', ARRAY['pioggia'], 720),
  ('Zaino weekend', 'Extra', ARRAY['weekend'], 730),
  ('Kit igiene travel size', 'Igiene', ARRAY['weekend'], 740),
  ('Beauty case compatto', 'Accessori', ARRAY['weekend'], 750),
  ('Packing Cubes', 'Accessori', ARRAY['lungo_raggio'], 760),
  ('Kit lavaggio panni', 'Igiene', ARRAY['lungo_raggio'], 770),
  ('Lucchetto extra', 'Accessori', ARRAY['lungo_raggio'], 780),
  ('Sacchetto panni sporchi', 'Extra', ARRAY['lungo_raggio'], 790),
  ('Multipresa da viaggio', 'Elettronica', ARRAY['lungo_raggio'], 800),
  ('Corda panni portatile', 'Extra', ARRAY['lungo_raggio'], 810),
  ('Pannolini', 'Bambini', ARRAY['famiglia'], 820),
  ('Salviette bimbo', 'Bambini', ARRAY['famiglia'], 830),
  ('Biberon', 'Bambini', ARRAY['famiglia'], 840),
  ('Ciuccio', 'Bambini', ARRAY['famiglia'], 850),
  ('Passeggino leggero', 'Bambini', ARRAY['famiglia'], 860),
  ('Marsupio porta bimbo', 'Bambini', ARRAY['famiglia'], 870),
  ('Giocattolo preferito', 'Bambini', ARRAY['famiglia'], 880),
  ('Latte in polvere', 'Bambini', ARRAY['famiglia'], 890),
  ('Bavaglino', 'Bambini', ARRAY['famiglia'], 900),
  ('Fasciatoio portatile', 'Bambini', ARRAY['famiglia'], 910),
  ('Crema barriera', 'Bambini', ARRAY['famiglia'], 920),
  ('Set pappa bimbo', 'Bambini', ARRAY['famiglia'], 930),
  ('Termos pappa', 'Bambini', ARRAY['famiglia'], 940),
  ('Monitor neonato', 'Bambini', ARRAY['famiglia'], 950),
  ('Cibo pet', 'Animali', ARRAY['pet'], 960),
  ('Ciotole pieghevoli', 'Animali', ARRAY['pet'], 970),
  ('Guinzaglio', 'Animali', ARRAY['pet'], 980),
  ('Pettorina', 'Animali', ARRAY['pet'], 990),
  ('Sacchetti igienici pet', 'Animali', ARRAY['pet'], 1000),
  ('Libretto sanitario pet', 'Animali', ARRAY['pet'], 1010),
  ('Cuccia portatile', 'Animali', ARRAY['pet'], 1020),
  ('Gioco preferito pet', 'Animali', ARRAY['pet'], 1030),
  ('Museruola', 'Animali', ARRAY['pet'], 1040),
  ('Spazzola pet', 'Animali', ARRAY['pet'], 1050),
  ('Salviette pet', 'Animali', ARRAY['pet'], 1060),
  ('Trasportino', 'Animali', ARRAY['pet'], 1070),
  ('Antidolorifico', 'Farmaci', ARRAY['farmacia'], 1080),
  ('Termometro digitale', 'Farmaci', ARRAY['farmacia'], 1090),
  ('Cerotti misti', 'Farmaci', ARRAY['farmacia'], 1100),
  ('Disinfettante', 'Farmaci', ARRAY['farmacia'], 1110),
  ('Fermenti lattici', 'Farmaci', ARRAY['farmacia'], 1120),
  ('Antidiarroico', 'Farmaci', ARRAY['farmacia'], 1130),
  ('Antistaminico', 'Farmaci', ARRAY['farmacia'], 1140),
  ('Farmaci cinetosi', 'Farmaci', ARRAY['farmacia'], 1150),
  ('Repellente insetti', 'Farmaci', ARRAY['farmacia'], 1160),
  ('Pomata post-puntura', 'Farmaci', ARRAY['farmacia'], 1170),
  ('Cerotti vesciche', 'Farmaci', ARRAY['farmacia'], 1180),
  ('Antiacido', 'Farmaci', ARRAY['farmacia'], 1190),
  ('Garze sterili', 'Farmaci', ARRAY['farmacia'], 1200),
  ('Gel muscolare', 'Farmaci', ARRAY['farmacia'], 1210),
  ('Integratori sali minerali', 'Farmaci', ARRAY['farmacia'], 1220),
  ('Spazzolino', 'Igiene', ARRAY['igiene_completa'], 1230),
  ('Dentifricio', 'Igiene', ARRAY['igiene_completa'], 1240),
  ('Deodorante', 'Igiene', ARRAY['igiene_completa'], 1250),
  ('Shampoo', 'Igiene', ARRAY['igiene_completa'], 1260),
  ('Bagnoschiuma', 'Igiene', ARRAY['igiene_completa'], 1270),
  ('Balsamo capelli', 'Igiene', ARRAY['igiene_completa'], 1280),
  ('Spazzola capelli', 'Igiene', ARRAY['igiene_completa'], 1290),
  ('Rasoio', 'Igiene', ARRAY['igiene_completa'], 1300),
  ('Schiuma da barba', 'Igiene', ARRAY['igiene_completa'], 1310),
  ('Kit manicure', 'Igiene', ARRAY['igiene_completa'], 1320),
  ('Assorbenti', 'Igiene', ARRAY['igiene_completa'], 1330),
  ('Crema idratante', 'Igiene', ARRAY['igiene_completa'], 1340),
  ('Fazzoletti di carta', 'Igiene', ARRAY['igiene_completa'], 1350),
  ('Salviettine igienizzanti', 'Igiene', ARRAY['igiene_completa'], 1360),
  ('Gel mani', 'Igiene', ARRAY['igiene_completa'], 1370),
  ('Cotton fioc', 'Igiene', ARRAY['igiene_completa'], 1380),
  ('Profumo', 'Igiene', ARRAY['igiene_completa'], 1390),
  ('Kit struccante', 'Igiene', ARRAY['igiene_completa'], 1400),
  ('Detergente intimo', 'Igiene', ARRAY['igiene_completa'], 1410),
  ('Flaconi viaggio silicone', 'Accessori', ARRAY['igiene_completa'], 1420),
  ('Intimo', 'Abbigliamento', ARRAY['abbigliamento_base'], 1430),
  ('Calze', 'Abbigliamento', ARRAY['abbigliamento_base'], 1440),
  ('T-shirt', 'Abbigliamento', ARRAY['abbigliamento_base'], 1450),
  ('Pantaloni', 'Abbigliamento', ARRAY['abbigliamento_base'], 1460),
  ('Pigiama', 'Abbigliamento', ARRAY['abbigliamento_base'], 1470),
  ('Canotta', 'Abbigliamento', ARRAY['abbigliamento_base'], 1480),
  ('Gonna', 'Abbigliamento', ARRAY['abbigliamento_base'], 1490),
  ('Vestito', 'Abbigliamento', ARRAY['abbigliamento_base'], 1500),
  ('Abbigliamento sportivo', 'Abbigliamento', ARRAY['abbigliamento_base'], 1510),
  ('Smartphone', 'Elettronica', ARRAY['elettronica_completa'], 1520),
  ('Caricabatterie smartphone', 'Elettronica', ARRAY['elettronica_completa'], 1530),
  ('Power bank alta capacità', 'Elettronica', ARRAY['elettronica_completa'], 1540),
  ('Cuffie bluetooth', 'Elettronica', ARRAY['elettronica_completa'], 1550),
  ('E-reader Kindle', 'Elettronica', ARRAY['elettronica_completa'], 1560),
  ('Macchina fotografica', 'Elettronica', ARRAY['elettronica_completa'], 1570),
  ('AirTag tracker', 'Elettronica', ARRAY['elettronica_completa'], 1580),
  ('Cavo USB extra', 'Elettronica', ARRAY['elettronica_completa'], 1590),
  ('Adattatore universale', 'Accessori', ARRAY['elettronica_completa'], 1600),
  ('Smartwatch', 'Elettronica', ARRAY['elettronica_completa'], 1610),
  ('Documento identità', 'Documenti', ARRAY['universal'], 1620),
  ('Carte di credito', 'Documenti', ARRAY['universal'], 1630),
  ('Contanti', 'Documenti', ARRAY['universal'], 1640),
  ('Assicurazione viaggio', 'Documenti', ARRAY['universal'], 1650),
  ('Caricabatterie universale', 'Elettronica', ARRAY['universal'], 1660),
  ('Farmaci base', 'Farmaci', ARRAY['universal'], 1670),
  ('Borraccia', 'Extra', ARRAY['universal'], 1680),
  ('Zaino da giorno', 'Extra', ARRAY['universal'], 1690),
  ('Lucchetto valigia', 'Accessori', ARRAY['universal'], 1700)
ON CONFLICT (name) DO NOTHING;

-- Migra item TD legacy da suitcase_items -> packing_template_items
INSERT INTO public.packing_template_items (template_id, category, name, sort_order, is_active)
SELECT
    si.suitcase_id,
    CASE
        WHEN lower(trim(si.category)) IN ('accessori & organizzazione', 'accessori') THEN 'Accessori'
        WHEN lower(trim(si.category)) = 'salute' THEN 'Farmaci'
        WHEN lower(trim(si.category)) = 'altro' THEN 'Extra'
        ELSE trim(si.category)
    END,
    trim(si.name),
    ROW_NUMBER() OVER (PARTITION BY si.suitcase_id ORDER BY si.category, si.name)::int * 10,
    true
FROM public.suitcase_items si
INNER JOIN public.suitcases s ON s.id = si.suitcase_id AND s.user_id IS NULL
WHERE COALESCE(si.is_ai_suggestion, false) = false
ON CONFLICT (template_id, category, name) DO NOTHING;

DELETE FROM public.suitcase_items si
USING public.suitcases s
WHERE si.suitcase_id = s.id AND s.user_id IS NULL;
