-- =============================================================================
-- MIGRATION: 20260705120001_seed_foundation_design_system_rules.sql
-- DESCRIZIONE: Seed regole Foundation modali (prototipo approvato)
-- SICUREZZA:   UPSERT su component_key
-- =============================================================================

INSERT INTO public.design_system_rules (
    section,
    element_name,
    component_key,
    font_family,
    text_size,
    font_weight,
    text_transform,
    tracking,
    color_class,
    line_height,
    effect_class,
    css_class,
    preview_text
)
VALUES
    (
        'foundation',
        'Overlay (aspetto visivo)',
        'foundation_modal_overlay',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-300 flex items-end sm:items-center justify-center p-0 sm:p-4 md:p-6',
        'Overlay'
    ),
    (
        'foundation',
        'Contenitore modale',
        'foundation_modal_container',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'relative w-full max-w-2xl bg-slate-900 border border-white/10 rounded-t-[2rem] sm:rounded-[2.5rem] shadow-[0_30px_100px_rgba(0,0,0,0.8)] overflow-hidden animate-in slide-in-from-bottom-4 sm:zoom-in-95 fade-in duration-300 flex flex-col max-h-[calc(100dvh-var(--header-height)-env(safe-area-inset-bottom,0px)-0.5rem)] sm:max-h-[90vh] pb-safe sm:pb-0',
        'Contenitore'
    ),
    (
        'foundation',
        'Barra header',
        'foundation_modal_header',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'flex items-center justify-between px-8 py-6 border-b border-white/5 shrink-0',
        'Header'
    ),
    (
        'foundation',
        'Corpo scrollabile',
        'foundation_modal_body',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'flex-1 overflow-y-auto overscroll-contain p-8 custom-scrollbar',
        'Body'
    ),
    (
        'foundation',
        'Barra footer',
        'foundation_modal_footer',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'px-4 sm:px-8 py-6 border-t border-white/5 bg-slate-900/50 shrink-0 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between min-w-0',
        'Footer'
    ),
    (
        'foundation',
        'Gruppo azioni footer',
        'foundation_modal_footer_actions',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'flex items-center justify-center gap-3 w-full',
        'Azioni footer'
    ),
    (
        'foundation',
        'Offset pulsante chiusura (X)',
        'foundation_modal_close_offset',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'top-6 right-8',
        'Offset X'
    ),
    (
        'foundation',
        'Contenitore icona header',
        'foundation_modal_header_icon_box',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'w-12 h-12 rounded-2xl bg-amber-500/10 flex items-center justify-center text-amber-500 border border-amber-500/20 shrink-0',
        'Icon box'
    ),
    (
        'foundation',
        'Dimensione icona header',
        'foundation_modal_header_icon_glyph',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'w-6 h-6',
        'Icona'
    ),
    (
        'foundation',
        'Titolo modale',
        'foundation_modal_title',
        'font-display',
        'text-xl',
        'font-bold',
        'uppercase',
        'tracking-wide',
        'text-white',
        'leading-none',
        'none',
        NULL,
        'Anteprima Foundation'
    ),
    (
        'foundation',
        'Titolo modale (Mobile)',
        'foundation_modal_title_mobile',
        'font-display',
        'text-lg',
        'font-bold',
        'uppercase',
        'tracking-wide',
        'text-white',
        'leading-none',
        'none',
        NULL,
        'Anteprima Foundation'
    ),
    (
        'foundation',
        'Sottotitolo modale',
        'foundation_modal_subtitle',
        'font-sans',
        NULL,
        NULL,
        'normal-case',
        NULL,
        NULL,
        NULL,
        'none',
        'text-[12px] font-medium text-slate-300/90',
        'Mockup tecnico dello standard modale TouringDiary'
    ),
    (
        'foundation',
        'Sottotitolo modale (Mobile)',
        'foundation_modal_subtitle_mobile',
        'font-sans',
        NULL,
        NULL,
        'normal-case',
        NULL,
        NULL,
        NULL,
        'none',
        'text-[12px] font-medium text-slate-300/90',
        'Mockup tecnico dello standard modale TouringDiary'
    ),
    (
        'foundation',
        'Titolo sezione',
        'foundation_section_title',
        'font-sans',
        'text-[12px]',
        'font-black',
        'uppercase',
        'tracking-[0.2em]',
        'text-amber-500',
        'leading-none',
        'none',
        NULL,
        'Titolo e testo'
    ),
    (
        'foundation',
        'Titolo sezione (Mobile)',
        'foundation_section_title_mobile',
        'font-sans',
        'text-[12px]',
        'font-black',
        'uppercase',
        'tracking-[0.2em]',
        'text-amber-500',
        'leading-none',
        'none',
        NULL,
        'Titolo e testo'
    ),
    (
        'foundation',
        'Icona titolo sezione',
        'foundation_section_title_icon',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'w-4 h-4 text-amber-500 shrink-0',
        'Icona sezione'
    ),
    (
        'foundation',
        'Descrizione sezione',
        'foundation_section_description',
        'font-sans',
        NULL,
        NULL,
        'normal-case',
        NULL,
        NULL,
        NULL,
        'none',
        'text-[12px] text-slate-300/90 font-medium',
        'Gerarchia tipografica del contenuto principale.'
    ),
    (
        'foundation',
        'Descrizione sezione (Mobile)',
        'foundation_section_description_mobile',
        'font-sans',
        NULL,
        NULL,
        'normal-case',
        NULL,
        NULL,
        NULL,
        'none',
        'text-[12px] text-slate-300/90 font-medium',
        'Gerarchia tipografica del contenuto principale.'
    ),
    (
        'foundation',
        'Testo corpo',
        'foundation_body_text',
        'font-sans',
        'text-[13px]',
        'font-medium',
        'normal-case',
        NULL,
        'text-slate-300',
        'leading-relaxed',
        'none',
        NULL,
        'Testo descrittivo nel corpo modale.'
    ),
    (
        'foundation',
        'Testo corpo (Mobile)',
        'foundation_body_text_mobile',
        'font-sans',
        'text-[13px]',
        'font-medium',
        'normal-case',
        NULL,
        'text-slate-300',
        'leading-relaxed',
        'none',
        NULL,
        'Testo descrittivo nel corpo modale.'
    ),
    (
        'foundation',
        'Card statica (superficie)',
        'foundation_card_surface',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'rounded-2xl border border-white/10 bg-slate-800/40 p-5 space-y-2',
        'Card'
    ),
    (
        'foundation',
        'Etichetta card',
        'foundation_card_label',
        'font-sans',
        'text-[12.5px]',
        'font-medium',
        'normal-case',
        NULL,
        'text-slate-400',
        NULL,
        'none',
        NULL,
        'Card secondaria'
    ),
    (
        'foundation',
        'Etichetta card (Mobile)',
        'foundation_card_label_mobile',
        'font-sans',
        'text-[12.5px]',
        'font-medium',
        'normal-case',
        NULL,
        'text-slate-400',
        NULL,
        'none',
        NULL,
        'Card secondaria'
    ),
    (
        'foundation',
        'Card selezionabile (base)',
        'foundation_selectable_card_base',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'p-5 rounded-3xl border text-left transition-all group relative flex flex-col h-full',
        'Card opzione'
    ),
    (
        'foundation',
        'Card selezionabile (selezionata)',
        'foundation_selectable_card_selected',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'bg-indigo-600/10 border-indigo-500/50 ring-1 ring-indigo-500/50',
        'Selezionata'
    ),
    (
        'foundation',
        'Card selezionabile (non selezionata)',
        'foundation_selectable_card_unselected',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'bg-white/5 border-white/5 hover:border-white/10',
        'Non selezionata'
    ),
    (
        'foundation',
        'Riga header card selezionabile',
        'foundation_selectable_card_header_row',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'flex items-center gap-3 mb-3 min-h-[3rem] pr-7',
        'Header card'
    ),
    (
        'foundation',
        'Badge selezione (base)',
        'foundation_selectable_badge_base',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'absolute top-5 right-5 w-5 h-5 rounded-full border flex items-center justify-center transition-all',
        'Badge'
    ),
    (
        'foundation',
        'Badge selezione (attivo)',
        'foundation_selectable_badge_selected',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'bg-indigo-500 border-indigo-500 shadow-lg shadow-indigo-500/40',
        'Badge attivo'
    ),
    (
        'foundation',
        'Badge selezione (inattivo)',
        'foundation_selectable_badge_unselected',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'border-white/10 bg-black/20',
        'Badge inattivo'
    ),
    (
        'foundation',
        'Spunta badge selezione',
        'foundation_selectable_check_icon',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'w-3 h-3 text-white stroke-[4]',
        'Spunta'
    ),
    (
        'foundation',
        'Icon box card (base)',
        'foundation_selectable_icon_box_base',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'w-10 h-10 rounded-xl flex items-center justify-center shrink-0 transition-colors',
        'Icon box'
    ),
    (
        'foundation',
        'Icon box card (selezionata)',
        'foundation_selectable_icon_box_selected',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'bg-indigo-500 text-white',
        'Icon box attivo'
    ),
    (
        'foundation',
        'Icon box card (non selezionata)',
        'foundation_selectable_icon_box_unselected',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'bg-slate-800 text-slate-400 group-hover:text-slate-200',
        'Icon box inattivo'
    ),
    (
        'foundation',
        'Titolo card selezionabile',
        'foundation_selectable_card_title',
        'font-sans',
        'text-[14px]',
        'font-bold',
        'normal-case',
        NULL,
        'text-white',
        'leading-snug',
        'none',
        NULL,
        'Valuta ed inserisci'
    ),
    (
        'foundation',
        'Titolo card selezionabile (Mobile)',
        'foundation_selectable_card_title_mobile',
        'font-sans',
        'text-[14px]',
        'font-bold',
        'normal-case',
        NULL,
        'text-white',
        'leading-snug',
        'none',
        NULL,
        'Valuta ed inserisci'
    ),
    (
        'foundation',
        'Descrizione card selezionabile',
        'foundation_selectable_card_description',
        'font-sans',
        'text-[12.5px]',
        'font-medium',
        'normal-case',
        NULL,
        'text-slate-400',
        NULL,
        'none',
        NULL,
        'Potrai valutare gli oggetti suggeriti prima di inserirli.'
    ),
    (
        'foundation',
        'Descrizione card selezionabile (Mobile)',
        'foundation_selectable_card_description_mobile',
        'font-sans',
        'text-[12.5px]',
        'font-medium',
        'normal-case',
        NULL,
        'text-slate-400',
        NULL,
        'none',
        NULL,
        'Potrai valutare gli oggetti suggeriti prima di inserirli.'
    ),
    (
        'foundation',
        'Pulsante Annulla / Indietro',
        'foundation_btn_cancel',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'w-36 sm:w-40 px-6 py-4 rounded-xl border border-rose-500/15 bg-rose-500/5 text-[10px] font-black text-rose-300/80 uppercase tracking-widest hover:text-rose-200 hover:border-rose-400/25 hover:bg-rose-500/10 transition-colors',
        'Annulla'
    ),
    (
        'foundation',
        'Pulsante primario (Conferma)',
        'foundation_btn_primary',
        '',
        NULL,
        NULL,
        'none',
        NULL,
        NULL,
        NULL,
        'none',
        'w-36 sm:w-40 px-6 py-4 rounded-2xl bg-indigo-600 text-white text-[10px] font-black uppercase tracking-widest whitespace-nowrap hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed shadow-xl shadow-indigo-500/20 transition-all active:scale-95 flex items-center justify-center gap-3',
        'Conferma'
    )
ON CONFLICT (component_key) DO UPDATE SET
    section = EXCLUDED.section,
    element_name = EXCLUDED.element_name,
    font_family = EXCLUDED.font_family,
    text_size = EXCLUDED.text_size,
    font_weight = EXCLUDED.font_weight,
    text_transform = EXCLUDED.text_transform,
    tracking = EXCLUDED.tracking,
    color_class = EXCLUDED.color_class,
    line_height = EXCLUDED.line_height,
    effect_class = EXCLUDED.effect_class,
    css_class = EXCLUDED.css_class,
    preview_text = EXCLUDED.preview_text;
